export type SurveyUnresolvedHistorySubmission = { id:number; source_id:number; questionnaire_source_id:number; questionnaire_id:number|null; customer_id:number|null; matched_by:string; source_channel:string; total_score:number; final_tags:unknown[]|null; submitted_at:string; created_at:string };
export type SurveyUnresolvedHistoryAnswer = { id:number; source_id:number; submission_id:number; submission_source_id:number; question_source_id:number; question_type:string; question_title_snapshot:string; selected_option_ids:unknown[]|null; selected_option_texts:unknown[]|null; selected_option_scores:unknown[]|null; selected_option_tags:unknown[]|null; text_value:string; score_contribution:number; created_at:string };
export type SurveyUnresolvedHistoryPage<T> = { items:T[]; total:number; limit:number; offset:number };
type Row=Record<string,unknown>;
const invalid=():never=>{throw new Error('问卷历史响应无效，未显示历史数据');};
const obj=(v:unknown):Row=>v&&typeof v==='object'&&!Array.isArray(v)?v as Row:invalid();
const int=(v:unknown,min?:number):v is number=>typeof v==='number'&&Number.isSafeInteger(v)&&(min===undefined||v>=min);
const text=(v:unknown):v is string=>typeof v==='string';
const date=(v:unknown):v is string=>text(v)&&Number.isFinite(Date.parse(v));
const only=(row:Row,fields:string[]):boolean=>Object.keys(row).length===fields.length&&Object.keys(row).every(key=>fields.includes(key));
const history=(row:Row):void=>{if(row.source!=='v1_history'||row.read_only!==true||row.real_external_call_executed!==false||row.definition_mapping!=='historical_source_only')invalid();};
const jsonArray=(v:unknown):v is unknown[]|null=>v===null||Array.isArray(v);
function pageArgs(limit:number,offset:number){if(!int(limit,1)||limit>100||!int(offset,0)||offset>2147483647)throw new Error('问卷历史分页无效');return{limit,offset};}
export function requireSurveyUnresolvedHistoryID(value:string|number):number{if((typeof value!=='string'&&typeof value!=='number')||(typeof value==='string'&&!/^[1-9]\d*$/.test(value))||!int(Number(value),1))throw new Error('问卷历史 ID 无效');return Number(value);}
function submission(value:unknown):SurveyUnresolvedHistorySubmission{const r=obj(value),f=['id','source_id','questionnaire_source_id','questionnaire_id','customer_id','matched_by','source_channel','total_score','final_tags','submitted_at','created_at'];if(!only(r,f)||!int(r.id,1)||!int(r.source_id)||!int(r.questionnaire_source_id)||!(r.questionnaire_id===null||int(r.questionnaire_id,1))||!(r.customer_id===null||int(r.customer_id,1))||!text(r.matched_by)||!text(r.source_channel)||typeof r.total_score!=='number'||!Number.isFinite(r.total_score)||!jsonArray(r.final_tags)||!date(r.submitted_at)||!date(r.created_at))invalid();return r as unknown as SurveyUnresolvedHistorySubmission;}
function answer(value:unknown):SurveyUnresolvedHistoryAnswer{const r=obj(value),f=['id','source_id','submission_id','submission_source_id','question_source_id','question_type','question_title_snapshot','selected_option_ids','selected_option_texts','selected_option_scores','selected_option_tags','text_value','score_contribution','created_at'];if(!only(r,f)||!int(r.id,1)||!['source_id','submission_id','submission_source_id','question_source_id'].every(key=>int(r[key]))||!['question_type','question_title_snapshot','text_value'].every(key=>text(r[key]))||!['selected_option_ids','selected_option_texts','selected_option_scores','selected_option_tags'].every(key=>jsonArray(r[key]))||typeof r.score_contribution!=='number'||!Number.isFinite(r.score_contribution)||!date(r.created_at))invalid();return r as unknown as SurveyUnresolvedHistoryAnswer;}
function readPage<T extends {id:number}>(value:unknown,limit:number,offset:number,convert:(value:unknown)=>T):SurveyUnresolvedHistoryPage<T>{const r=obj(value);if(!only(r,['source','read_only','real_external_call_executed','definition_mapping','items','total','limit','offset'])||!Array.isArray(r.items)||!int(r.total,0)||r.limit!==limit||r.offset!==offset)invalid();history(r);const rawItems=r.items as unknown[];const items:T[]=rawItems.map(convert);if(items.length!==Math.min(limit,Math.max(0,(r.total as number)-offset))||new Set(items.map((item:T)=>item.id)).size!==items.length)invalid();return{items,total:r.total as number,limit,offset};}
function readDetail(value:unknown,id:number):SurveyUnresolvedHistorySubmission{const r=obj(value);if(!only(r,['source','read_only','real_external_call_executed','definition_mapping','item']))invalid();history(r);const item=submission(r.item);if(item.id!==id)invalid();return item;}
export type SurveyUnresolvedHistoryTransport={listSubmissions:(query:{questionnaire_id?:number;limit:number;offset:number})=>Promise<unknown>;getSubmission:(id:number)=>Promise<unknown>;listAnswers:(id:number,query:{limit:number;offset:number})=>Promise<unknown>};
export function surveyUnresolvedHistoryReader(transport:SurveyUnresolvedHistoryTransport){return{async listSubmissions(limit=20,offset=0,questionnaireID?:number){const p=pageArgs(limit,offset);const questionnaire=questionnaireID===undefined?undefined:requireSurveyUnresolvedHistoryID(questionnaireID);const result=readPage(await transport.listSubmissions({...p,questionnaire_id:questionnaire}),limit,offset,submission);if(questionnaire!==undefined&&result.items.some(item=>item.questionnaire_id!==questionnaire))invalid();return result;},async getSubmission(id:string|number){const value=requireSurveyUnresolvedHistoryID(id);return readDetail(await transport.getSubmission(value),value);},async listAnswers(submissionID:string|number,limit=20,offset=0){const p=pageArgs(limit,offset),id=requireSurveyUnresolvedHistoryID(submissionID),result=readPage(await transport.listAnswers(id,p),limit,offset,answer);if(result.items.some(item=>item.submission_id!==id))invalid();return result;}};}
