import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { spawn, spawnSync } from 'node:child_process';
import { chromiumStartupDiagnostic, chromiumStartupTimeoutMS } from '../../internal/webshell/chromium_launch.mjs';

const baseURL=process.env.AICRM_QUESTIONNAIRE_LIST_TEST_URL;
const username=process.env.AICRM_QUESTIONNAIRE_LIST_TEST_USERNAME;
const password=process.env.AICRM_QUESTIONNAIRE_LIST_TEST_PASSWORD;
const screenshotDirectory=process.env.AICRM_QUESTIONNAIRE_LIST_SCREENSHOT_DIR;
if(!/^https:\/\//.test(baseURL||'')||!username||!password||!path.isAbsolute(screenshotDirectory||'')) throw new Error('questionnaire list read-state Chromium configuration is invalid');
const sleep=(ms)=>new Promise(resolve=>setTimeout(resolve,ms));
function chrome(){for(const candidate of [process.env.AICRM_CHROMIUM_BINARY,process.env.CHROME_BIN,process.platform==='darwin'?'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome':'','google-chrome','google-chrome-stable','chromium','chromium-browser'].filter(Boolean)){if(candidate.includes('/')){try{if(spawnSync(candidate,['--version'],{stdio:'ignore'}).status===0)return candidate;}catch{}}else if(spawnSync('which',[candidate],{stdio:'ignore'}).status===0)return candidate;}throw new Error('Chromium binary is unavailable');}
class CDP { constructor(socket){this.socket=socket;this.id=0;this.pending=new Map();socket.addEventListener('message',event=>{const message=JSON.parse(String(event.data));const pending=this.pending.get(message.id);if(!pending)return;this.pending.delete(message.id);message.error?pending.reject(new Error(`CDP ${message.error.code}: ${message.error.message}`)):pending.resolve(message.result||{});});} call(method,params={}){return new Promise((resolve,reject)=>{const id=++this.id;this.pending.set(id,{resolve,reject});this.socket.send(JSON.stringify({id,method,params}));});} close(){for(const pending of this.pending.values())pending.reject(new Error('CDP closed'));this.pending.clear();this.socket.close();}}
function binaryDiagnostic(browser,stderr){return chromiumStartupDiagnostic({profile,exitCode:browser?.exitCode,signalCode:browser?.signalCode,stderr});}
async function devtools(profile,browser,stderr){const deadline=Date.now()+chromiumStartupTimeoutMS;while(Date.now()<deadline){try{const port=String(await fs.readFile(path.join(profile,'DevToolsActivePort'),'utf8')).split('\n')[0];if(/^\d+$/.test(port))return `http://127.0.0.1:${port}`;}catch{}if(browser?.exitCode!==null)break;await sleep(50);}throw new Error(binaryDiagnostic(browser,stderr));}
async function evaluate(cdp,expression,label='page'){const result=await cdp.call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(result.exceptionDetails){const type=String(result.exceptionDetails.exception?.className||'RuntimeException').slice(0,80);const detail=String(result.exceptionDetails.exception?.description||result.exceptionDetails.text||'unknown').replace(/\s+/g,' ').slice(0,240);throw new Error(`${label} evaluation failed: ${type}: ${detail}`);}return result.result?.value;}
async function waitFor(cdp,expression,label){for(let attempt=0;attempt<180;attempt++){if(await evaluate(cdp,expression,label))return;await sleep(50);}throw new Error(`${label}: ${await evaluate(cdp,`JSON.stringify({path:location.pathname,text:document.body.innerText.slice(-1000)})`,'diagnostic')}`);}
async function capture(cdp,name,selector){await evaluate(cdp,`document.querySelector(${JSON.stringify(selector)})?.scrollIntoView({block:'center',inline:'nearest'});true`,'position screenshot state');await sleep(40);await fs.mkdir(screenshotDirectory,{recursive:true,mode:0o700});const shot=await cdp.call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await fs.writeFile(path.join(screenshotDirectory,name),Buffer.from(shot.data,'base64'),{mode:0o600});}
async function viewport(cdp,width){await cdp.call('Emulation.setDeviceMetricsOverride',{width,height:800,deviceScaleFactor:1,mobile:false});}
async function assertGeometry(cdp,selector,label){const result=await evaluate(cdp,`(()=>{const target=document.querySelector(${JSON.stringify(selector)});target?.scrollIntoView({block:'center',inline:'nearest'});const rect=target?.getBoundingClientRect();return {found:Boolean(target),visible:!!target&&getComputedStyle(target).display!=='none',overflow:document.documentElement.scrollWidth>innerWidth,width:innerWidth,top:rect?.top,bottom:rect?.bottom,viewport:innerHeight};})()`,label);if(!result?.found||!result.visible||result.overflow||!(result.top>=0&&result.top<result.viewport&&result.bottom>0))throw new Error(`${label}: ${JSON.stringify(result)}`);}
async function setMode(cdp,mode){const result=await evaluate(cdp,`fetch('/__test/questionnaire-list-mode?mode='+${JSON.stringify(mode)},{headers:{'X-AICRM-Questionnaire-Test-Control':'1'}}).then(response=>response.status)`, 'set mode');if(result!==204)throw new Error(`fixture mode ${mode} status=${result}`);}
async function reload(cdp){await cdp.call('Page.reload',{ignoreCache:true});}
async function stop(child){if(!child||child.exitCode!==null||child.signalCode!==null)return;child.kill('SIGTERM');await Promise.race([new Promise(resolve=>child.once('exit',resolve)),sleep(3000)]);if(child.exitCode===null&&child.signalCode===null){child.kill('SIGKILL');await Promise.race([new Promise(resolve=>child.once('exit',resolve)),sleep(1000)]);}}
const profile=await fs.mkdtemp(path.join(os.tmpdir(),'aicrm-questionnaire-list-'));let browser;let cdp;let stderr='';let failure;
try{
 browser=spawn(chrome(),['--headless=new','--no-sandbox','--remote-debugging-port=0',`--user-data-dir=${profile}`,'--no-first-run','--no-default-browser-check','--disable-background-networking','--ignore-certificate-errors','--allow-insecure-localhost','about:blank'],{stdio:['ignore','ignore','pipe']});browser.stderr.on('data',chunk=>{stderr=(stderr+String(chunk)).slice(-2048);});
 const tab=await(await fetch(`${await devtools(profile,browser,stderr)}/json/new?about:blank`,{method:'PUT'})).json();const socket=new WebSocket(tab.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{socket.addEventListener('open',resolve,{once:true});socket.addEventListener('error',reject,{once:true});});cdp=new CDP(socket);await cdp.call('Page.enable');await cdp.call('Runtime.enable');await cdp.call('Network.enable');
 await cdp.call('Page.addScriptToEvaluateOnNewDocument',{source:`(()=>{const original=window.fetch.bind(window);window.__surveyListReads=[];window.fetch=(input,init)=>{const raw=typeof input==='string'?input:input&&input.url;const path=String(raw||'');if(path.includes('/api/admin/questionnaires'))window.__surveyListReads.push(path);return original(input,init);};})();`});
 await viewport(cdp,1280);await cdp.call('Page.navigate',{url:`${baseURL}/login?next=${encodeURIComponent('/admin/questionnaires')}`});await waitFor(cdp,"Boolean(document.querySelector('form[action=\"/login\"] input[name=\"login_csrf_token\"]'))",'login');await evaluate(cdp,`(()=>{document.querySelector('input[name="username"]').value=${JSON.stringify(username)};document.querySelector('input[name="password"]').value=${JSON.stringify(password)};document.querySelector('form[action="/login"]').requestSubmit();return true;})()`,'submit login');
 await waitFor(cdp,"location.pathname==='/admin/questionnaires'",'cold navigation route');await waitFor(cdp,"Boolean(document.querySelector('[data-surface-table-read-state=\"error\"] button'))",'cold 503 retry state');await assertGeometry(cdp,'[data-surface-table-read-state="error"]','cold 503 geometry');
 await setMode(cdp,'normal');await evaluate(cdp,"document.querySelector('[data-surface-table-read-state=\"error\"] button').click();true",'retry cold 503');await waitFor(cdp,"Boolean(document.querySelector('[data-surface-table-read-state=\"empty\"]'))",'empty after retry');await assertGeometry(cdp,'[data-surface-table-read-state="empty"]','empty 1280 geometry');await capture(cdp,'questionnaire-empty-1280.png','[data-surface-table-read-state="empty"]');
 const create=await evaluate(cdp,`(()=>{const csrf=(document.cookie.match(/(?:^|; )aicrm_csrf=([^;]+)/)||[])[1];return fetch('/api/admin/questionnaires',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':'questionnaire-list-browser-create-0001','X-CSRF-Token':decodeURIComponent(csrf||'')},body:JSON.stringify({name:'浏览器问卷目录',title:'浏览器问卷目录',description:'',answer_display_mode:'all_in_one',assessment_enabled:false,assessment_config:{},slug:'browser-list-read-state',questions:[{type:'textarea',title:'测试问题',required:true,sort_order:0,placeholder_text:'',validation:{},options:[]}],score_rules:[]})}).then(response=>response.status);})()`,'create fixture questionnaire');if(create!==200)throw new Error(`create fixture questionnaire status=${create}`);
 await reload(cdp);await waitFor(cdp,"document.body?.textContent?.includes('浏览器问卷目录')",'real PostgreSQL questionnaire row');await viewport(cdp,1440);await evaluate(cdp,`(()=>{const input=document.querySelector('input[placeholder*="问卷名称"]');input.focus();input.value='中文输入法草稿';input.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));input.dispatchEvent(new Event('input',{bubbles:true}));return window.__surveyListReads.length;})()`,'start IME composition');await sleep(100);const imeReads=await evaluate(cdp,"window.__surveyListReads.length",'IME reads');if(imeReads!==1)throw new Error(`IME input unexpectedly re-read questionnaire directory: ${imeReads}`);await evaluate(cdp,`(()=>{const input=document.querySelector('input[placeholder*="问卷名称"]');input.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));const select=document.querySelector('select');select.value='enabled';select.dispatchEvent(new Event('change',{bubbles:true}));return {value:select.value};})()`,'local no-match status filter');await waitFor(cdp,"Boolean(document.querySelector('[data-surface-table-read-state=\"no-match\"]'))",'local no-match state');await assertGeometry(cdp,'[data-surface-table-read-state="no-match"]','no-match 1440 geometry');await capture(cdp,'questionnaire-no-match-1440.png','[data-surface-table-read-state="no-match"]');
 await evaluate(cdp,`(()=>{const select=document.querySelector('select');select.value='';select.dispatchEvent(new Event('change',{bubbles:true}));return true;})()`,'clear local filter');await waitFor(cdp,"document.body?.textContent?.includes('浏览器问卷目录')",'restored real row');await setMode(cdp,'503');await viewport(cdp,1280);await reload(cdp);await waitFor(cdp,"Boolean(document.querySelector('[data-surface-table-read-state=\"error\"] button'))&&!document.body?.textContent?.includes('浏览器问卷目录')",'cold 503 retry after reload');await capture(cdp,'questionnaire-retry-1280.png','[data-surface-table-read-state="error"]');await setMode(cdp,'normal');await evaluate(cdp,"document.querySelector('[data-surface-table-read-state=\"error\"] button').click();true",'retry preserved row');await waitFor(cdp,"!document.querySelector('[data-surface-table-read-state]')&&document.body?.textContent?.includes('浏览器问卷目录')",'retry restores current list');
 await setMode(cdp,'403');await viewport(cdp,1440);await reload(cdp);await waitFor(cdp,"Boolean(document.querySelector('[data-surface-table-read-state=\"error\"]'))",'403 state');const forbidden=await evaluate(cdp,"(()=>{const state=document.querySelector('[data-surface-table-read-state=\"error\"]');return {retry:Boolean(state?.querySelector('button')),hasRow:document.body?.textContent?.includes('浏览器问卷目录')};})()",'403 boundary');if(forbidden.retry||forbidden.hasRow)throw new Error(`403 retained retry or authorized rows: ${JSON.stringify(forbidden)}`);await assertGeometry(cdp,'[data-surface-table-read-state="error"]','forbidden 1440 geometry');await capture(cdp,'questionnaire-forbidden-1440.png','[data-surface-table-read-state="error"]');
 console.log('questionnaire_list_read_state_chromium: PASS');
}catch(error){failure=error;}finally{try{cdp?.close();}catch{}await stop(browser);try{await fs.rm(profile,{recursive:true,force:true,maxRetries:0});}catch{}if(failure)throw failure;}
