import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { JSDOM } from 'jsdom';

const dom = new JSDOM('<!doctype html><button id="trigger">选择群</button>', { url: 'https://test.invalid' });
Object.assign(globalThis, { window: dom.window, document: dom.window.document, Element: dom.window.Element, HTMLElement: dom.window.HTMLElement, KeyboardEvent: dom.window.KeyboardEvent, Event: dom.window.Event, DOMException: dom.window.DOMException, AbortController: dom.window.AbortController });
const bundle = await build({ stdin: { contents: "export { openGroupPicker } from './web/v3/shared/ui/groupPickerAdapter';", resolveDir: process.cwd(), sourcefile: 'group-picker-test.ts' }, bundle: true, format: 'esm', platform: 'node', write: false, target: 'es2020' });
const { openGroupPicker } = await import(`data:text/javascript;base64,${Buffer.from(bundle.outputFiles[0].text).toString('base64')}`);
const flush = () => new Promise(resolve => setTimeout(resolve, 0));
const calls = [];
let committed; let cancelled = 0;
const trigger = document.querySelector('#trigger'); trigger.focus();
openGroupPicker({ source: 'plan-41', scope: 'group_ops.plan_group_assets', selectedRecords: [{ chat_reference: 'bound-missing', display_name: '历史绑定', unavailable_reason: '群目录状态待确认，仍保留已绑定记录。' }], loadPage: async ({ query, cursor, signal }) => { calls.push({ query, cursor, aborted: signal.aborted }); if (query === '故障') throw new Error('群目录暂不可用'); if (cursor === 'next') return { items: [{ chat_reference: 'group-2', display_name: '第二群' }] }; return { items: [{ chat_reference: 'group-1', display_name: '第一群' }, { chat_reference: 'forbidden', display_name: '不可选群', unavailable_reason: '当前负责人不可管理此群。' }], nextCursor: 'next' }; }, onCommit: value => { committed = value; }, onCancel: ({ saveAttempted }) => { assert.equal(saveAttempted, false, 'a pure draft cancel must not imply a persisted save'); cancelled += 1; } });
await flush();
const mask = document.querySelector('[data-v3-selection-session="group"]');
assert.ok(mask); assert.equal(mask.dataset.selectionSource, 'plan-41'); assert.equal(mask.dataset.selectionScope, 'group_ops.plan_group_assets');
const search = mask.querySelector('[data-v3-picker-search-input]');
assert.equal(search.matches('[data-group-picker-search]'), false, 'V3 search cannot be captured by frozen group picker');
search.dispatchEvent(new dom.window.CompositionEvent('compositionstart', { bubbles: true }));
const imeEscape = new KeyboardEvent('keydown', { bubbles: true, cancelable: true, key: 'Escape' });
search.dispatchEvent(imeEscape);
assert.ok(document.querySelector('[data-v3-selection-session="group"]'), 'IME Escape must not close the selection dialog');
assert.equal(imeEscape.defaultPrevented, false, 'IME Escape remains available to the native candidate session');
search.dispatchEvent(new dom.window.CompositionEvent('compositionend', { bubbles: true }));
await flush();
const hiddenControl = document.createElement('div'); hiddenControl.hidden = true; hiddenControl.innerHTML = '<button type="button">hidden control</button>'; mask.querySelector('.group-ops__modal').append(hiddenControl);
const visibleBeforeHidden = mask.querySelector('[data-v3-group-confirm]'); visibleBeforeHidden.focus();
visibleBeforeHidden.dispatchEvent(new KeyboardEvent('keydown', { bubbles: true, cancelable: true, key: 'Tab' }));
assert.notEqual(document.activeElement.textContent, 'hidden control', 'focus trap excludes controls hidden by an ancestor');
const beforeIME = calls.length; search.value = '中文候选'; search.dispatchEvent(new dom.window.CompositionEvent('compositionstart', { bubbles: true })); search.dispatchEvent(new Event('input', { bubbles: true })); search.dispatchEvent(new dom.window.CompositionEvent('compositionend', { bubbles: true })); const candidate = new KeyboardEvent('keydown', { bubbles: true, cancelable: true, key: 'Enter' }); Object.defineProperty(candidate, 'keyCode', { value: 229 }); search.dispatchEvent(candidate); await flush(); assert.equal(calls.length, beforeIME); assert.equal(candidate.defaultPrevented, false);
search.value = '第一'; search.dispatchEvent(new Event('input', { bubbles: true })); assert.equal(calls.length, beforeIME); search.dispatchEvent(new KeyboardEvent('keydown', { bubbles: true, key: 'Enter' })); await flush(); assert.deepEqual(calls.at(-1), { query: '第一', cursor: undefined, aborted: false });
assert.match(mask.textContent, /群目录状态待确认/); assert.match(mask.textContent, /当前负责人不可管理/);
mask.querySelector('[data-v3-group-key$="group-1"]').click(); assert.equal(mask.querySelector('[data-v3-group-key$="group-1"]').getAttribute('aria-pressed'), 'true', 'selected group result exposes its toggle state'); const removeBound = mask.querySelector('[data-v3-group-remove]'); removeBound.focus(); mask.querySelector('[data-v3-group-key$="group-2"]')?.focus(); mask.querySelector('[data-v3-group-more]').click(); await flush(); assert.equal(calls.at(-1).cursor, 'next'); mask.querySelector('[data-v3-group-key$="group-2"]').click(); const remove = mask.querySelector('[data-v3-group-remove]'); remove.focus(); remove.click(); await flush(); assert.equal(document.activeElement.dataset.v3GroupRemove.endsWith(':group-1'), true, 'removing a selected group retains focus in the dialog');
search.value = '故障'; search.dispatchEvent(new Event('input', { bubbles: true })); search.dispatchEvent(new KeyboardEvent('keydown', { bubbles: true, key: 'Enter' })); await flush(); assert.match(mask.textContent, /群目录暂不可用/); assert.match(mask.textContent, /第二群/, 'failure keeps the usable selection page');
mask.querySelector('[data-v3-group-confirm]').click(); await flush(); assert.deepEqual(committed.added.map(x => x.chat_reference), ['group-1', 'group-2']); assert.deepEqual(committed.removed.map(x => x.chat_reference), ['bound-missing']); assert.equal(document.querySelector('[data-v3-selection-session="group"]'), null); assert.equal(document.activeElement, trigger);
openGroupPicker({ source: 'plan-41', scope: 'group_ops.plan_group_assets', selectedRecords: [], loadPage: async () => ({ items: [{ chat_reference: 'group-1', display_name: '第一群' }] }), onCommit: () => { throw new Error('不应提交'); }, onCancel: () => { cancelled += 1; } }); await flush(); const second = document.querySelector('[data-v3-selection-session="group"]'); second.querySelector('[data-v3-group-key]').click(); second.querySelector('[data-v3-group-cancel]').click(); assert.equal(cancelled, 1, 'cancel does not commit'); assert.equal(document.querySelector('[data-v3-selection-session="group"]'), null);
let accessCommit = 0;
openGroupPicker({ source: 'plan-41', scope: 'group_ops.plan_group_assets', selectedRecords: [{ chat_reference: 'bound-missing', display_name: '历史绑定' }], accessLossMessage: error => error?.status === 403 ? '群目录权限已失效；已绑定群仍可查看，请取消后重新登录。' : undefined, loadPage: async ({ query }) => { if (query === '权限') { const error = new Error('forbidden'); error.status = 403; throw error; } return { items: [] }; }, onCommit: () => { accessCommit += 1; } });
await flush();
const access = document.querySelector('[data-v3-selection-session="group"]');
const accessSearch = access.querySelector('[data-v3-picker-search-input]');
accessSearch.value = '权限'; accessSearch.dispatchEvent(new Event('input', { bubbles: true })); accessSearch.dispatchEvent(new KeyboardEvent('keydown', { bubbles: true, key: 'Enter' }));
await flush();
assert.match(access.textContent, /权限已失效/, 'caller-classified 403 remains explicit');
assert.match(access.textContent, /历史绑定/, '403 retains existing group bindings for inspection');
assert.equal(access.querySelector('[data-v3-group-confirm]').disabled, true, 'access loss blocks commit');
access.querySelector('[data-v3-group-cancel]').click();
assert.equal(accessCommit, 0);

let delayedGroup403;
const delayedGroupLoader = ({ query }) => {
  if (query === '旧权限') return new Promise((_resolve, reject) => { delayedGroup403 = reject; });
  return Promise.resolve({ items: [{ chat_reference: 'group-new', display_name: query === '新结果' ? '新结果群' : '普通群' }] });
};
openGroupPicker({ source: 'plan-race', scope: 'group_ops.plan_group_assets', selectedRecords: [], accessLossMessage: error => error?.status === 403 ? '群目录权限已失效；已绑定群仍可查看，请取消后重新登录。' : undefined, loadPage: delayedGroupLoader, onCommit: () => {} });
await flush();
const delayedGroup = document.querySelector('[data-v3-selection-session="group"]');
const delayedGroupSearch = delayedGroup.querySelector('[data-v3-picker-search-input]');
delayedGroupSearch.value = '旧权限'; delayedGroupSearch.dispatchEvent(new Event('input', { bubbles: true })); delayedGroupSearch.dispatchEvent(new KeyboardEvent('keydown', { bubbles: true, key: 'Enter' }));
delayedGroupSearch.value = '新结果'; delayedGroupSearch.dispatchEvent(new Event('input', { bubbles: true })); delayedGroupSearch.dispatchEvent(new KeyboardEvent('keydown', { bubbles: true, key: 'Enter' }));
await flush();
delayedGroup403(Object.assign(new Error('forbidden'), { status: 403 }));
await flush(); await flush();
assert.equal(delayedGroup.querySelector('[data-v3-group-confirm]').disabled, false, 'a late old 403 must not lock the newer group result');
assert.doesNotMatch(delayedGroup.textContent, /权限已失效/, 'late old group 403 has no visible effect after newer success');
delayedGroupSearch.value = '旧权限'; delayedGroupSearch.dispatchEvent(new Event('input', { bubbles: true })); delayedGroupSearch.dispatchEvent(new KeyboardEvent('keydown', { bubbles: true, key: 'Enter' }));
delayedGroup.querySelector('[data-v3-group-cancel]').click();
openGroupPicker({ source: 'plan-race', scope: 'group_ops.plan_group_assets', selectedRecords: [], loadPage: delayedGroupLoader, onCommit: () => {} });
await flush();
const reopenedGroup = document.querySelector('[data-v3-selection-session="group"]');
delayedGroup403(Object.assign(new Error('forbidden'), { status: 403 }));
await flush(); await flush();
assert.equal(reopenedGroup.querySelector('[data-v3-group-confirm]').disabled, false, 'a delayed closed group loader must not lock a reopened session');
reopenedGroup.querySelector('[data-v3-group-cancel]').click();

let saveCalls = 0;
let resolveSave;
openGroupPicker({ source: 'plan-save', scope: 'group_ops.plan_group_assets', selectedRecords: [], loadPage: async () => ({ items: [{ chat_reference: 'save-group', display_name: '保存群' }] }), onCommit: () => { saveCalls += 1; return new Promise((resolve) => { resolveSave = resolve; }); } });
await flush();
const saving = document.querySelector('[data-v3-selection-session="group"]');
saving.querySelector('[data-v3-group-key]').click();
saving.querySelector('[data-v3-group-confirm]').click();
saving.querySelector('[data-v3-group-confirm]').click();
saving.querySelector('[data-v3-group-reload]').click();
saving.querySelector('[data-v3-group-cancel]').click();
assert.equal(saveCalls, 1, 'save locks duplicate confirmation');
assert.equal(saving.querySelector('[data-v3-group-confirm]').disabled, true, 'save visibly locks confirm');
assert.match(saving.textContent, /正在保存群聊/, 'save lock tells the operator why refresh and close are unavailable');
resolveSave(); await flush(); await flush();
assert.equal(document.querySelector('[data-v3-selection-session="group"]'), null, 'successful save closes only after the caller resolves');

let failedSaveCalls = 0;
openGroupPicker({ source: 'plan-failure', scope: 'group_ops.plan_group_assets', selectedRecords: [], loadPage: async () => ({ items: [{ chat_reference: 'failure-group', display_name: '失败保留群' }] }), onCommit: () => { failedSaveCalls += 1; throw new Error('已实际保存：添加 failure-group；请重试未完成步骤。'); } });
await flush();
const failedSave = document.querySelector('[data-v3-selection-session="group"]');
failedSave.querySelector('[data-v3-group-key]').click(); failedSave.querySelector('[data-v3-group-confirm]').click(); await flush();
assert.match(failedSave.textContent, /已实际保存：添加 failure-group/, 'partial failure is visible without discarding the draft');
assert.ok(failedSave.querySelector('[data-v3-group-remove]'), 'partial failure keeps the selected draft for retry');
failedSave.querySelector('[data-v3-group-confirm]').click(); await flush();
assert.equal(failedSaveCalls, 2, 'partial failure permits an explicit retry with the same draft');
failedSave.querySelector('[data-v3-group-cancel]').click();

dom.window.close(); console.log('group picker adapter: scoped records, IME, paging, race-safe access loss, save lock, failure retention, commit, cancel PASS');
