import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { fileURLToPath } from 'node:url';
import { buildTestBrowserBundle } from '../scripts/test-browser-bundle.mjs';

const bundle = await buildTestBrowserBundle(fileURLToPath(new URL('./distributionAdmin.ts', import.meta.url)));
const delay = (ms = 15) => new Promise((resolve) => setTimeout(resolve, ms));
async function waitFor(check, message) { for (let attempt = 0; attempt < 100; attempt++) { if (check()) return; await delay(); } throw new Error(message); }
const json = (body, status = 200) => new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } });
function enter(window, input, properties = {}) { const event = new window.KeyboardEvent('keydown', { bubbles: true, cancelable: true, key: 'Enter', code: 'Enter' }); for (const [name, value] of Object.entries(properties)) Object.defineProperty(event, name, { value }); input.dispatchEvent(event); return event; }
function resolveConfirmation(result) { const current = confirmations.shift(); assert.ok(current, 'confirmation must be opened before it can resolve'); current.resolve(result); }
const calls = [];
const confirmations = [];
let recoveryAttempts = 0;
let overviewMode = 'ready';
let holdOverview = false;
const pendingOverview = [];
let holdLists = false;
let holdOrderDetail = false;
let failOrders = false;
let failDistributors = false;
let failExceptions = false;
let malformedMoreOnce = false;
const pendingLists = [];
const pendingOrderDetails = [];
let holdDisable = false;
const pendingDisables = [];
const dom = new JSDOM('<!doctype html><header class="admin-topbar"><div class="admin-topbar-head"><h1 class="admin-page-title">分销管理</h1></div></header><main id="distribution-admin-root"></main>', { url: 'https://crm.example/admin/distribution', runScripts: 'outside-only', pretendToBeVisual: true, beforeParse(window) {
  window.Response = Response; window.Headers = Headers; Object.defineProperty(window.crypto, 'randomUUID', { value: globalThis.crypto.randomUUID.bind(globalThis.crypto) }); window.AICRMConfirmation = { confirm: (options) => new Promise((resolve) => confirmations.push({ options, resolve })) };
	window.HTMLDialogElement.prototype.showModal = function showModal() { this.open = true; }; window.HTMLDialogElement.prototype.close = function close() { this.open = false; this.dispatchEvent(new window.Event('close')); };
  window.fetch = async (input, init = {}) => { const url = new URL(String(input), window.location.href); calls.push({ path: url.pathname, search: url.search, method: init.method || 'GET', body: init.body || '', idempotencyKey: new Headers(init.headers).get('Idempotency-Key') || '' });
	if (url.pathname === '/api/admin/overview') {
		if (holdOverview) return new Promise((resolve) => pendingOverview.push({ url, resolve }));
		if (overviewMode === 'exception_missing') return json({ distribution: { status: 'ready', currency: 'CNY', period_paid_sales_minor: 1200, current_unsettled_minor: 0, current_settled_minor: 330 }, todos: { status: 'ready', items: [] } });
		if (overviewMode === 'exception_negative') return json({ distribution: { status: 'ready', currency: 'CNY', period_paid_sales_minor: 1200, current_unsettled_minor: 0, current_settled_minor: 330, current_exception_order_count: -1 }, todos: { status: 'ready', items: [] } });
		if (overviewMode === 'zero') return json({ distribution: { status: 'zero', currency: 'CNY', period_paid_sales_minor: 0, period_initial_commission_minor: 0, period_commission_count: 0, current_unsettled_minor: 0, current_settled_minor: 0, current_exception_order_count: 0 }, todos: { status: 'zero', items: [{ code: 'distribution_exceptions', count: 0, href: '/admin/distribution' }] } });
		if (overviewMode === 'missing') return json({ distribution: { status: 'data_missing', reason_code: 'distribution_not_configured', currency: 'CNY', period_paid_sales_minor: 0, period_initial_commission_minor: 0, period_commission_count: 0, current_unsettled_minor: 0, current_settled_minor: 0, current_exception_order_count: 0 }, todos: { status: 'data_missing', reason_code: 'distribution_not_configured', items: [] } });
		if (overviewMode === 'failed') return json({ distribution: { status: 'failed', reason_code: 'distribution_summary_unavailable' }, todos: { status: 'failed', reason_code: 'distribution_summary_unavailable', items: [] } });
		if (overviewMode === 'malformed') return json({ distribution: {}, todos: {} });
		return json({ distribution: { status: 'ready', as_of: '2026-09-15T00:00:00Z', currency: 'CNY', period_paid_sales_minor: 1200, period_initial_commission_minor: 0, period_commission_count: 2, current_unsettled_minor: 0, current_settled_minor: 330, current_exception_order_count: 1 }, todos: { status: 'ready', as_of: '2026-09-15T00:00:00Z', items: [{ code: 'unrelated_todo', count: 99, href: '/admin' }, { code: 'distribution_exceptions', count: 2, href: '/admin/distribution' }] } });
	}
	if (url.pathname === '/api/admin/distribution/distributors/9') return json({ distributor: { id: 9, display_name: '<img src=x onerror=window.__nameXss=1>', public_no: 'D-9', enabled: true, receiver_ready: false, receiver_status: 'receiver_final_failed' }, earnings: { gross_paid_sales_minor: 19900, unsettled_payable_minor: 3000, paid_commission_minor: 0, currency: 'CNY' } });
	if (url.pathname === '/api/admin/distribution/distributors/9/orders') { if (url.searchParams.get('cursor') === '10') { if (malformedMoreOnce) { malformedMoreOnce = false; return json({ items: {} }); } return json({ items: [{ attribution_id: 21, order_reference: 'O-19', product_name: '增长课' }], next_cursor: '' }); } return json({ items: Array.from({ length: 10 }, (_, index) => ({ attribution_id: 11 + index, order_reference: index === 0 ? 'O-9' : `O-${9 + index}`, product_name: '增长课' })), next_cursor: '10' }); }
	if (url.pathname === '/api/admin/distribution/orders/11' || url.pathname === '/api/admin/distribution/orders/12') {
		const response = () => json({ order: { attribution_id: 11, order_reference: 'O-9', product_name: '增长课', distributor_display_name: '<img src=x onerror=window.__nameXss=1>', qualification_evidence_reference: 'evidence:1', policy_version: '', rate_basis_points: null, wait_days: undefined, paid_minor: null, currency: 'CNY' }, commission: { status: 'held', initial_minor: null, successful_refund_minor: null, current_payable_minor: null, paid_minor: null, paid_confirmed_at: '', due_at: 'not-a-date', currency: 'CNY' }, adjustments: [{ kind: 'buyer_refund', delta_minor: -3300, resulting_payable_minor: 3327, reason: 'buyer_refund', source_reference: 'refund:9', occurred_at: '2026-09-15T00:00:00Z' }], settlements: [{ reference: 'SET-9', amount_minor: 3327, currency: 'CNY', state: 'receiver_succeeded', provider_deadline_at: '2026-09-22T00:00:00Z', settlement_confirmed_at: '2026-09-14T01:00:00Z', created_at: '2026-09-14T00:00:00Z', updated_at: '2026-09-15T00:00:00Z' }], exceptions: [{ exception_id: 51, kind: 'buyer_refund_after_paid', status: 'open', amount_minor: 1200, currency: 'CNY', reason: 'buyer_refund_after_paid', updated_at: '2026-09-15T00:00:00Z' }] });
		if (holdOrderDetail) return new Promise((resolve) => pendingOrderDetails.push({ resolve, response }));
		return response();
	}
	if (url.pathname === '/api/admin/distribution/exceptions/51') return json({ exception_id: 51, order_reference: 'O-9', kind: 'buyer_refund_after_paid', status: 'recovery_recorded', unpaid_due_minor: 1200, already_paid_minor: 3327, amount_minor: 1200, currency: 'CNY', reason: 'buyer_refund_after_paid', evidence_reference: 'receipt:51', actor_scope: 'access:7', created_at: '2026-09-14T00:00:00Z', updated_at: '2026-09-15T00:00:00Z', audit: [{ event_type: 'distribution.recovery_recorded.v1', actor_scope: 'access:7', amount_minor: 1200, evidence_reference: 'receipt:51', occurred_at: '2026-09-15T00:00:00Z' }] });
	if (['/api/admin/distribution/distributors', '/api/admin/distribution/orders', '/api/admin/distribution/exceptions'].includes(url.pathname)) {
		if (holdLists) return new Promise((resolve) => pendingLists.push({ url, resolve }));
		if (failOrders && url.pathname === '/api/admin/distribution/orders') throw new Error('orders unavailable');
		if (failDistributors && url.pathname === '/api/admin/distribution/distributors') throw new Error('distributors unavailable');
		if (failExceptions && url.pathname === '/api/admin/distribution/exceptions') throw new Error('exceptions unavailable');
	}
	if (/\/disable$/.test(url.pathname) && holdDisable) return new Promise((resolve) => pendingDisables.push(resolve));
    if (url.pathname === '/api/admin/distribution/distributors') return json({ items: [{ id: 9, display_name: '<img src=x onerror=window.__nameXss=1>', agreement_version: '2026-09', enabled: true, receiver_ready: false, receiver_status: 'receiver_final_failed', registered_at: '2026-09-14T00:00:00Z', version: 3 }, { id: 10, display_name: '', agreement_version: '2026-09', enabled: false, receiver_ready: true, receiver_status: '', registered_at: '2026-09-14T00:00:00Z', version: 4 }], next_cursor: '' });
    if (url.pathname === '/api/admin/distribution/orders') return json({ items: [{ attribution_id: 11, order_reference: 'O-9', item_line: '1', product_id: 7, product_type: 'standard_product', product_name: '增长课', distributor_display_name: '<img src=x onerror=window.__nameXss=1>', qualification_state: 'eligible', qualification_evidence_reference: '', policy_version: '', rate_basis_points: null, wait_days: undefined, paid_minor: null, currency: 'CNY', attributed_at: 'not-a-date' }, { attribution_id: 12, order_reference: 'O-10', item_line: '1', product_id: 8, product_type: 'standard_product', product_name: '增长课', distributor_display_name: '另一分销员', qualification_state: 'eligible', qualification_evidence_reference: '', policy_version: '', rate_basis_points: null, wait_days: undefined, paid_minor: null, currency: 'CNY', attributed_at: 'not-a-date' }], next_cursor: '' });
	if (url.pathname === '/api/admin/distribution/exceptions') return json({ items: [{ exception_id: 'x1', commission_id: 'c1', distributor_display_name: '<img src=x onerror=window.__nameXss=1>', order_reference: 'O-9', kind: 'qualification_revoked', status: 'open', unpaid_due_minor: 12, already_paid_minor: 33, amount_minor: 12, currency: 'CNY', reason: 'payment_receiver_receipt_limit', payment_instruction_reference: 'pi:1', created_at: '2026-09-14T00:00:00Z', updated_at: '2026-09-14T00:00:00Z', version: 4, can_reconcile: true, can_record_recovery: true, can_record_merchant_liability: true }], next_cursor: '' });
    if (/\/recoveries$/.test(url.pathname) && recoveryAttempts++ === 0) throw new Error('connection interrupted');
    if (/\/disable$|\/reconcile$|\/recoveries$|\/merchant-liabilities$/.test(url.pathname)) return json({ ok: true });
    return json({ error: 'not_found' }, 404);
  };
} });
dom.window.eval(bundle); await waitFor(() => dom.window.document.body.textContent.includes('未设置昵称'), 'distributor list did not render nickname fallback');
await waitFor(() => dom.window.document.querySelector('.distribution-summary')?.textContent.includes('¥12.00'), 'ready distribution overview did not render');
assert.equal(dom.window.document.querySelectorAll('.admin-topbar .admin-page-title').length, 1, 'the shell keeps the only distribution page title');
assert.equal(dom.window.document.querySelectorAll('#distribution-admin-root h1').length, 0, 'the distribution body must not render a duplicate page title');
const headerActions = dom.window.document.querySelector('[data-page-header-actions="distribution-admin"]');
assert.ok(headerActions, 'distribution actions mount in the existing shell topbar');
assert.deepEqual([...headerActions.querySelectorAll('a,button')].map((action) => action.textContent), ['申请二维码'], 'the header retains only the QR entry');
let summaryText = dom.window.document.querySelector('.distribution-summary')?.textContent || '';
assert.equal(summaryText.includes('分销概览'), true, 'the overview keeps its section title');
assert.equal(summaryText.includes('期内初始佣金'), false, 'the overview removes the redundant initial commission metric');
assert.equal(summaryText.includes('佣金笔数'), false, 'the overview removes the redundant commission count metric');
assert.equal(dom.window.document.querySelectorAll('.distribution-summary-card').length, 4, 'the overview presents exactly four metrics');
const exceptionSummary = [...dom.window.document.querySelectorAll('.distribution-summary-card')].find((card) => card.textContent.includes('待处理异常订单'));
assert.equal(exceptionSummary?.textContent.includes('1'), true, 'the overview uses the owned distinct open exception order count');
assert.equal(exceptionSummary?.textContent.includes('2'), false, 'the overview must not reuse the exception-record todo count');
assert.equal(exceptionSummary?.textContent.includes('99'), false, 'an unrelated todo must not be shown as an exception order');
const stableHeaderAction = [...headerActions.querySelectorAll('button')].find((action) => action.textContent === '申请二维码');
stableHeaderAction.focus();
dom.window.document.querySelector('[data-distribution-summary-period="7d"]')?.dispatchEvent(new dom.window.MouseEvent('click', { bubbles: true }));
await waitFor(() => dom.window.document.querySelector('[data-distribution-summary-period="7d"]')?.getAttribute('aria-pressed') === 'true', 'summary redraw did not complete');
assert.equal(dom.window.document.activeElement, stableHeaderAction, 'content redraw must preserve the stable topbar action focus');
assert.equal(dom.window.document.querySelector('[data-page-header-actions="distribution-admin"] button:nth-of-type(1)'), stableHeaderAction, 'content redraw must not replace the header action node');
overviewMode = 'zero';
dom.window.document.querySelector('[data-distribution-summary-period="today"]')?.dispatchEvent(new dom.window.MouseEvent('click', { bubbles: true }));
await waitFor(() => [...dom.window.document.querySelectorAll('.distribution-summary-card')].every((card) => card.textContent.includes('0')), 'zero overview did not render actual zero values');
summaryText = dom.window.document.querySelector('.distribution-summary')?.textContent || '';
assert.equal(summaryText.includes('当前口径内未形成'), false, 'zero state must not add a redundant summary footnote');
overviewMode = 'missing';
dom.window.document.querySelector('[data-distribution-summary-period="30d"]')?.dispatchEvent(new dom.window.MouseEvent('click', { bubbles: true }));
await waitFor(() => [...dom.window.document.querySelectorAll('.distribution-summary-card')].every((card) => card.textContent.includes('待确认')), 'missing overview facts did not remain unknown');
assert.equal((dom.window.document.querySelector('.distribution-summary')?.textContent || '').includes('¥0.00'), false, 'missing facts must not be rendered as currency zero');
overviewMode = 'exception_missing';
dom.window.document.querySelector('[data-distribution-summary-period="today"]')?.dispatchEvent(new dom.window.MouseEvent('click', { bubbles: true }));
await waitFor(() => [...dom.window.document.querySelectorAll('.distribution-summary-card')].find((card) => card.textContent.includes('待处理异常订单'))?.textContent.includes('待确认'), 'a missing exception-order count must remain unknown');
overviewMode = 'exception_negative';
dom.window.document.querySelector('[data-distribution-summary-period="7d"]')?.dispatchEvent(new dom.window.MouseEvent('click', { bubbles: true }));
await waitFor(() => [...dom.window.document.querySelectorAll('.distribution-summary-card')].find((card) => card.textContent.includes('待处理异常订单'))?.textContent.includes('待确认'), 'a negative exception-order count must remain unknown');
overviewMode = 'failed';
dom.window.document.querySelector('[data-distribution-summary-period="7d"]')?.dispatchEvent(new dom.window.MouseEvent('click', { bubbles: true }));
await waitFor(() => [...dom.window.document.querySelectorAll('.distribution-summary-card')].every((card) => card.textContent.includes('读取失败')), 'failed overview facts did not expose their failed state');
overviewMode = 'malformed';
dom.window.document.querySelector('[data-distribution-summary-period="30d"]')?.dispatchEvent(new dom.window.MouseEvent('click', { bubbles: true }));
await waitFor(() => (dom.window.document.querySelector('.distribution-summary')?.textContent || '').includes('分销汇总响应无效，请重试。'), 'a malformed overview response must expose a retryable failure');
assert.equal([...dom.window.document.querySelectorAll('.distribution-summary-card')].every((card) => card.textContent.includes('读取失败')), true, 'a malformed overview response must not remain in an apparent loading state');
overviewMode = 'ready';
;[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '重新读取')?.click();
await waitFor(() => dom.window.document.querySelector('.distribution-summary')?.textContent.includes('¥12.00'), 'overview did not restore from its explicit test state');
holdOverview = true;
dom.window.document.querySelector('[data-distribution-summary-period="30d"]')?.dispatchEvent(new dom.window.MouseEvent('click', { bubbles: true }));
dom.window.document.querySelector('[data-distribution-summary-period="today"]')?.dispatchEvent(new dom.window.MouseEvent('click', { bubbles: true }));
await waitFor(() => pendingOverview.length === 2, 'overview race requests did not start');
assert.equal((dom.window.document.querySelector('.distribution-summary')?.textContent || '').includes('¥12.00'), false, 'a new period must not show prior-period values while loading');
pendingOverview[1].resolve(json({ distribution: { status: 'ready', as_of: '2026-09-15T00:00:00Z', currency: 'CNY', period_paid_sales_minor: 3400, period_initial_commission_minor: 0, period_commission_count: 1, current_unsettled_minor: 0, current_settled_minor: 0, current_exception_order_count: 0 }, todos: { status: 'ready', as_of: '2026-09-15T00:00:00Z', items: [{ code: 'distribution_exceptions', count: 3 }] } }));
await waitFor(() => dom.window.document.querySelector('.distribution-summary')?.textContent.includes('¥34.00'), 'latest overview response did not render');
pendingOverview[0].resolve(json({ distribution: { status: 'ready', as_of: '2026-09-15T00:00:00Z', currency: 'CNY', period_paid_sales_minor: 9900, period_initial_commission_minor: 0, period_commission_count: 9, current_unsettled_minor: 0, current_settled_minor: 0, current_exception_order_count: 0 }, todos: { status: 'ready', as_of: '2026-09-15T00:00:00Z', items: [{ code: 'distribution_exceptions', count: 9 }] } }));
await delay();
assert.equal((dom.window.document.querySelector('.distribution-summary')?.textContent || '').includes('¥99.00'), false, 'a stale overview response must not replace the latest period');
assert.equal(dom.window.document.querySelector('[data-distribution-summary-period="today"]')?.getAttribute('aria-pressed'), 'true', 'the selected period must remain aligned with its response');
holdOverview = false;
assert.equal(dom.window.document.body.textContent.includes('用户昵称'), true, 'distributor list must lead with user nickname');
assert.equal(dom.window.document.body.textContent.includes('客户编号'), false, 'distributor list must not present synthetic customer references');
assert.equal(dom.window.document.body.textContent.includes('D-9'), false, 'distribution number belongs only in the detail drawer');
assert.equal(dom.window.document.querySelectorAll('img').length, 0, 'nickname must remain text, never HTML');
assert.equal(dom.window.__nameXss, undefined, 'nickname must not execute markup');
assert.equal(dom.window.document.body.textContent.includes('收款准备失败，需管理员核验支付侧状态'), true, 'receiver final failure must be a clear Chinese readiness state');
const crossTabDraft = dom.window.document.querySelector('input[aria-label="仅筛选当前已加载页"]');
crossTabDraft.value = '跨标签草稿'; crossTabDraft.dispatchEvent(new dom.window.Event('input', { bubbles: true }));
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '订单').click();
await waitFor(() => dom.window.document.body.textContent.includes('O-9'), 'orders tab did not open while preserving a draft');
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '分销员').click();
await waitFor(() => dom.window.document.body.textContent.includes('未设置昵称'), 'distributors tab did not restore after preserving a draft');
const restoredCrossTabDraft = dom.window.document.querySelector('input[aria-label="仅筛选当前已加载页"]');
assert.equal(restoredCrossTabDraft, crossTabDraft, 'each tab must retain its own stable filter node');
assert.equal(restoredCrossTabDraft.value, '跨标签草稿', 'switching tabs must retain an uncommitted draft');
assert.equal(dom.window.document.body.textContent.includes('未设置昵称'), true, 'an uncommitted cross-tab draft must not filter rows');
const writesBeforeStaleDisableConfirmation = calls.filter((call) => call.method !== 'GET').length;
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '停用').click();
await waitFor(() => confirmations.length === 1, 'disable must freeze its distributor target before confirmation');
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '订单').click();
await waitFor(() => dom.window.document.body.textContent.includes('O-9'), 'switching tabs during confirmation did not complete');
resolveConfirmation({ confirmed: true, values: { reason: '已失效目标' } });
await delay(80);
assert.equal(calls.filter((call) => call.method !== 'GET').length, writesBeforeStaleDisableConfirmation, 'a cross-tab confirmation must not write its stale distributor target');
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '分销员').click();
await waitFor(() => dom.window.document.body.textContent.includes('未设置昵称'), 'distributor list did not recover after stale confirmation');
restoredCrossTabDraft.value = '';
const distributionCallsBeforeFilter = calls.filter((call) => call.path === '/api/admin/distribution/distributors').length;
const filter = dom.window.document.querySelector('input[aria-label="仅筛选当前已加载页"]');
filter.focus(); filter.value = '无匹配当前页记录'; filter.setSelectionRange(filter.value.length, filter.value.length);
filter.dispatchEvent(new dom.window.CompositionEvent('compositionstart', { bubbles: true }));
filter.dispatchEvent(new dom.window.Event('input', { bubbles: true }));
assert.equal(dom.window.document.querySelector('input[aria-label="仅筛选当前已加载页"]'), filter, 'IME draft must keep the filter input node stable');
assert.equal(dom.window.document.body.textContent.includes('未设置昵称'), true, 'IME draft must not redraw current-page rows');
const overviewRequestsBeforeComposition = pendingOverview.length;
holdOverview = true;
dom.window.document.querySelector('[data-distribution-summary-period="7d"]')?.dispatchEvent(new dom.window.MouseEvent('click', { bubbles: true }));
await waitFor(() => pendingOverview.length === overviewRequestsBeforeComposition + 1, 'overview reload did not start during IME composition');
assert.equal(dom.window.document.querySelector('input[aria-label="仅筛选当前已加载页"]'), filter, 'an overview reload must not replace a composing filter input');
assert.equal(filter.value, '无匹配当前页记录', 'an overview reload must retain the uncommitted IME draft');
pendingOverview[pendingOverview.length - 1].resolve(json({ distribution: { status: 'ready', as_of: '2026-09-15T00:00:00Z', currency: 'CNY', period_paid_sales_minor: 1200, period_initial_commission_minor: 0, period_commission_count: 2, current_unsettled_minor: 0, current_settled_minor: 330, current_exception_order_count: 1 }, todos: { status: 'ready', as_of: '2026-09-15T00:00:00Z', items: [{ code: 'distribution_exceptions', count: 2 }] } }));
await waitFor(() => dom.window.document.querySelector('.distribution-summary')?.textContent.includes('¥12.00'), 'delayed overview response did not render');
assert.equal(dom.window.document.querySelector('input[aria-label="仅筛选当前已加载页"]'), filter, 'a delayed overview response must not replace a composing filter input');
holdOverview = false;
const candidateEnter = enter(dom.window, filter, { keyCode: 229 });
assert.equal(candidateEnter.defaultPrevented, false, 'IME candidate confirmation must keep browser behavior');
assert.equal(dom.window.document.body.textContent.includes('未设置昵称'), true, 'IME candidate confirmation must not submit the filter');
filter.dispatchEvent(new dom.window.CompositionEvent('compositionend', { bubbles: true }));
await delay();
const committedEnter = enter(dom.window, filter);
assert.equal(committedEnter.defaultPrevented, true, 'a deliberate Enter must commit the current-page filter');
await waitFor(() => dom.window.document.body.textContent.includes('当前已加载页没有匹配记录。'), 'current-page filter did not apply locally');
assert.equal(calls.filter((call) => call.path === '/api/admin/distribution/distributors').length, distributionCallsBeforeFilter, 'current-page filter must not request a later server page');
const restoredFilter = dom.window.document.querySelector('input[aria-label="仅筛选当前已加载页"]');
assert.equal(dom.window.document.activeElement, restoredFilter, 'the committed filter redraw must restore focus to the rebuilt input');
restoredFilter.value = ''; restoredFilter.dispatchEvent(new dom.window.Event('input', { bubbles: true }));
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '筛选').click();
await waitFor(() => dom.window.document.body.textContent.includes('未设置昵称'), 'clearing current-page filter did not restore loaded rows');
holdLists = true;
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '订单').click();
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '分销员').click();
await waitFor(() => pendingLists.length === 2, 'tab race requests did not start');
pendingLists[1].resolve(json({ items: [{ id: 88, display_name: '最新分销员', agreement_version: '2026-09', enabled: true, receiver_ready: true, registered_at: '2026-09-15T00:00:00Z', version: 1 }], next_cursor: '' }));
await waitFor(() => dom.window.document.body.textContent.includes('最新分销员'), 'latest tab response did not render');
pendingLists[0].resolve(json({ items: [{ attribution_id: 77, order_reference: '过期订单', product_name: '过期商品' }], next_cursor: '' }));
await delay();
assert.equal(dom.window.document.body.textContent.includes('过期订单'), false, 'a stale orders response must not overwrite the distributors tab');
assert.equal(dom.window.document.body.textContent.includes('用户昵称'), true, 'a stale tab response must not reinterpret rows under another table heading');
holdLists = false;
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '分销员').click();
await waitFor(() => dom.window.document.body.textContent.includes('未设置昵称'), 'distributor fixture did not restore after race coverage');
failOrders = true;
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '订单').click();
await waitFor(() => dom.window.document.body.textContent.includes('网络不可用，未确认任何分销操作。'), 'failed orders read did not expose its selected-tab failure state');
assert.equal(dom.window.document.body.textContent.includes('O-9'), true, 'a failed orders read must retain its own prior successful snapshot');
assert.equal(dom.window.document.body.textContent.includes('未设置昵称'), false, 'a failed orders read must not reuse distributor rows under order headings');
failOrders = false;
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '订单').click();
await waitFor(() => dom.window.document.body.textContent.includes('O-9'), 'orders snapshot did not load before refresh-retention coverage');
failOrders = true;
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '订单').click();
await waitFor(() => dom.window.document.body.textContent.includes('网络不可用，未确认任何分销操作。'), 'failed orders refresh did not expose its failure state');
assert.equal(dom.window.document.body.textContent.includes('O-9'), true, 'a failed refresh must retain the selected tab’s prior successful rows');
failOrders = false;
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '分销员').click();
await waitFor(() => dom.window.document.body.textContent.includes('未设置昵称'), 'distributor fixture did not restore after failed tab coverage');
const writesBeforeAccessRevocation = calls.filter((call) => call.method !== 'GET').length;
holdLists = true;
const pendingBefore403 = pendingLists.length;
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '分销员').click();
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '分销员').click();
await waitFor(() => pendingLists.length === pendingBefore403 + 2, 'same-scope list requests did not start for revocation coverage');
pendingLists[pendingBefore403 + 1].resolve(json({ error: 'permission_denied' }, 403));
await waitFor(() => dom.window.document.body.textContent.includes('当前管理员无权查看此记录。'), 'a current 403 must expose the revoked list scope');
assert.equal(dom.window.document.body.textContent.includes('未设置昵称'), false, 'a 403 must clear previously authorized distributor rows');
assert.equal([...dom.window.document.querySelectorAll('button')].some((button) => button.textContent === '停用'), false, 'a 403-cleared list must not retain mutation controls');
pendingLists[pendingBefore403].resolve(json({ items: [{ id: 901, display_name: '过期授权记录', agreement_version: '2026-09', enabled: true, version: 1 }], next_cursor: '' }));
await delay();
assert.equal(dom.window.document.body.textContent.includes('过期授权记录'), false, 'an older success must not restore a 403-revoked list scope');
assert.equal(calls.filter((call) => call.method !== 'GET').length, writesBeforeAccessRevocation, 'access revocation handling must not send a mutation');
holdLists = false;
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '分销员').click();
await waitFor(() => dom.window.document.body.textContent.includes('未设置昵称'), 'a later authorized distributor read did not restore the list');
holdLists = true;
const pendingBefore401 = pendingLists.length;
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '分销员').click();
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '订单').click();
await waitFor(() => pendingLists.length === pendingBefore401 + 2, 'interleaved list reads did not start before session loss');
pendingLists[pendingBefore401 + 1].resolve(json({ error: 'unauthenticated' }, 401));
await waitFor(() => dom.window.document.body.textContent.includes('登录已失效，请重新登录后再读取。'), 'a 401 must clear the session-bound list state');
assert.equal(dom.window.document.body.textContent.includes('O-9'), false, 'session loss must remove a previously authorized order snapshot');
pendingLists[pendingBefore401].resolve(json({ items: [{ id: 902, display_name: '迟到会话记录', agreement_version: '2026-09', enabled: true, version: 1 }], next_cursor: '' }));
await delay();
assert.equal(dom.window.document.body.textContent.includes('迟到会话记录'), false, 'an old pre-401 success must not restore the session-bound cache');
assert.equal(calls.filter((call) => call.method !== 'GET').length, writesBeforeAccessRevocation, 'session loss handling must not send a mutation');
holdLists = false;
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '分销员').click();
await waitFor(() => dom.window.document.body.textContent.includes('未设置昵称'), 'authorized reads must recover after the test session state is restored');
const applicationTrigger = [...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '申请二维码');
applicationTrigger.focus();
applicationTrigger.click();
await waitFor(() => dom.window.document.querySelector('dialog')?.textContent.includes('分销申请二维码'), 'application QR dialog did not render');
const applicationDialog = [...dom.window.document.querySelectorAll('dialog')].find((dialog) => dialog.textContent.includes('分销申请二维码'));
assert.equal(applicationDialog?.querySelector('input[readonly]')?.value, 'https://crm.example/distribution', 'application QR dialog must show the caller-owned URL');
assert.equal(applicationDialog?.classList.contains('shared-detail-drawer--center'), true, 'the shared QR dialog must preserve centered share presentation');
assert.ok(applicationDialog?.querySelector('.shared-qr-dialog__code svg'), 'application QR dialog must render the shared QR presentation');
const copyApplicationAction = [...applicationDialog.querySelectorAll('button')].find((button) => button.textContent === '复制申请链接');
assert.equal((copyApplicationAction).__dcBound, true, 'the shared QR callback remains an owned real action');
applicationDialog.dispatchEvent(new dom.window.MouseEvent('click', { bubbles: true }));
assert.equal(applicationDialog.isConnected, false, 'the QR backdrop must close the centered presentation');
assert.equal(dom.window.document.activeElement, applicationTrigger, 'closing the QR backdrop must restore trigger focus');
applicationTrigger.click();
await waitFor(() => dom.window.document.querySelector('dialog')?.textContent.includes('分销申请二维码'), 'application QR dialog did not reopen after a backdrop close');
applicationTrigger.click();
assert.equal(dom.window.document.querySelectorAll('dialog[data-shared-qr-dialog="true"]').length, 1, 'reopening the QR presentation must replace its existing dialog');
[...dom.window.document.querySelector('dialog[data-shared-qr-dialog="true"]').querySelectorAll('button')].find((button) => button.textContent === '关闭').click();
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '查看详情').click();
await waitFor(() => dom.window.document.body.textContent.includes('关联推广订单'), 'distributor detail did not render');
assert.equal(dom.window.document.body.textContent.includes('D-9'), true, 'distribution number is an auxiliary detail fact only');
assert.equal([...dom.window.document.querySelectorAll('button')].filter((button) => button.textContent.includes('· 增长课')).length, 10, 'first server page must show exactly ten related orders');
malformedMoreOnce = true;
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '加载更多订单').click();
await waitFor(() => dom.window.document.body.textContent.includes('读取更多关联订单失败：关联推广订单响应无效'), 'malformed related-order response did not leave an actionable retry');
const retryMore = [...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '重试读取更多订单');
assert.equal(retryMore?.isConnected, true, 'malformed related-order response must retain the retry control in the drawer');
retryMore.click();
await waitFor(() => dom.window.document.body.textContent.includes('O-19 · 增长课'), 'related-order load more did not append the next server page');
assert.equal(calls.some((call) => call.path === '/api/admin/distribution/distributors/9/orders' && call.search === '?limit=10&cursor=10'), true, 'related-order continuation must pass the server cursor');
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === 'O-9 · 增长课').click();
await waitFor(() => dom.window.document.body.textContent.includes('买家退款调整') && dom.window.document.body.textContent.includes('SET-9'), 'order detail did not render concrete adjustment and settlement facts');
assert.equal(dom.window.document.body.textContent.includes('创建时间'), true, 'settlement detail must show its persisted created time');
assert.equal(dom.window.document.body.textContent.includes('退款/资格调整：'), false, 'order detail cannot replace facts with aggregate counts');
const orderDrawer = [...dom.window.document.querySelectorAll('dialog')].find((dialog) => dialog.textContent.includes('推广订单详情'));
assert.equal(orderDrawer?.textContent.includes('待确认'), true, 'empty policy and invalid time facts must stay explicitly unknown');
assert.equal(orderDrawer?.textContent.includes('商品实付—'), true, 'missing amount must not be coerced into zero in the detail drawer');
assert.equal(orderDrawer?.textContent.includes('变动金额-¥33.00'), true, 'an adjustment without a row currency must inherit the owned commission currency');
assert.equal(orderDrawer?.textContent.includes('调整后应付¥33.27'), true, 'an adjustment payable amount must remain visible with the owned commission currency');
const settlementRecord = [...orderDrawer.querySelectorAll('.distribution-detail-record')].find((record) => record.textContent.includes('SET-9'));
assert.equal(settlementRecord?.textContent.includes('系统分账成功时间'), true, 'receiver success must expose the audited settlement confirmation fact');
assert.equal(settlementRecord?.textContent.includes('2026年9月14日 09:00'), true, 'settlement success must use settlement_confirmed_at');
assert.equal(settlementRecord?.textContent.includes('2026年9月15日 08:00'), true, 'the record update time remains separately labeled and cannot stand in for success');
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent.includes('退款后已分账')).click();
await waitFor(() => dom.window.document.body.textContent.includes('管理员') && dom.window.document.body.textContent.includes('已登记追回'), 'exception detail did not render readable audit facts');
assert.equal(dom.window.document.body.textContent.includes('access:7') || dom.window.document.body.textContent.includes('distribution.recovery_recorded.v1'), false, 'exception detail must not expose internal actor or event codes');
assert.equal(dom.window.document.body.textContent.includes('尚欠应付¥12.00') && dom.window.document.body.textContent.includes('金额¥12.00'), true, 'exception money and its audit must inherit the Distribution-owned exception currency');
[...dom.window.document.querySelectorAll('button')].filter((button) => button.textContent === '关闭').forEach((button) => button.click());
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '订单').click();
await waitFor(() => dom.window.document.body.textContent.includes('O-9'), 'order list did not restore before detail authorization coverage');
holdOrderDetail = true;
const pendingDetailBefore403 = pendingOrderDetails.length;
const orderDetailButtons = [...dom.window.document.querySelectorAll('button')].filter((button) => button.textContent === '查看详情');
orderDetailButtons[0].click();
orderDetailButtons[1].click();
await waitFor(() => pendingOrderDetails.length === pendingDetailBefore403 + 2, 'interleaved detail reads did not start');
pendingOrderDetails[pendingDetailBefore403 + 1].resolve(json({ error: 'permission_denied' }, 403));
await waitFor(() => dom.window.document.body.textContent.includes('当前管理员无权查看此记录。'), 'a current detail 403 must replace the drawer facts');
assert.equal(dom.window.document.body.textContent.includes('SET-9'), false, 'a current detail 403 must not leave prior order facts visible');
pendingOrderDetails[pendingDetailBefore403].resolve(pendingOrderDetails[pendingDetailBefore403].response());
await delay();
assert.equal(dom.window.document.body.textContent.includes('SET-9'), false, 'an older detail success must not repopulate a revoked drawer');
assert.equal(calls.filter((call) => call.method !== 'GET').length, writesBeforeAccessRevocation, 'detail authorization handling must not send a mutation');
holdOrderDetail = false;
[...dom.window.document.querySelectorAll('button')].filter((button) => button.textContent === '关闭').forEach((button) => button.click());
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '订单').click();
await waitFor(() => dom.window.document.body.textContent.includes('O-9'), 'order list did not recover before closed-drawer race coverage');
holdOrderDetail = true;
const pendingClosedDetail = pendingOrderDetails.length;
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '查看详情').click();
await waitFor(() => pendingOrderDetails.length === pendingClosedDetail + 1, 'closed-drawer detail read did not start');
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '关闭').click();
holdLists = true;
const pendingOtherTab = pendingLists.length;
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '分销员').click();
await waitFor(() => pendingLists.length === pendingOtherTab + 1, 'other-tab list read did not start while the closed detail remained pending');
pendingOrderDetails[pendingClosedDetail].resolve(json({ error: 'permission_denied' }, 403));
pendingLists[pendingOtherTab].resolve(json({ items: [{ id: 903, display_name: '切换后分销员', agreement_version: '2026-09', enabled: true, receiver_ready: true, version: 1 }], next_cursor: '' }));
await waitFor(() => dom.window.document.body.textContent.includes('切换后分销员'), 'a closed stale detail must not invalidate another tab\'s current list read');
assert.equal(dom.window.document.body.textContent.includes('正在读取分销员记录…'), false, 'a closed stale detail must not leave another tab loading');
assert.equal(calls.filter((call) => call.method !== 'GET').length, writesBeforeAccessRevocation, 'a closed detail 403 must not send a mutation');
holdOrderDetail = false;
holdLists = false;
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '分销员').click();
await waitFor(() => dom.window.document.body.textContent.includes('未设置昵称'), 'distributor list did not restore after detail authorization coverage');
failDistributors = true;
const writesBeforeCancelledDisable = calls.filter((call) => call.method !== 'GET').length;
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '停用').click();
await waitFor(() => confirmations.length === 1, 'disable must open one shared confirmation');
assert.match(confirmations[0].options.title, /停用分销员/, 'disable uses the shared confirmation contract');
assert.match(confirmations[0].options.description, /分销员 ID 9/, 'disable confirmation identifies its frozen distributor target');
resolveConfirmation({ confirmed: false });
await delay();
assert.equal(calls.filter((call) => call.method !== 'GET').length, writesBeforeCancelledDisable, 'cancelled disable must not write');
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '停用').click();
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '停用')?.click();
await waitFor(() => confirmations.length === 1, 'duplicate disable click must not open a second confirmation');
resolveConfirmation({ confirmed: true, values: { reason: '不符合当前协议' } });
await waitFor(() => calls.some((call) => call.path.endsWith('/disable')), 'disable did not call the real endpoint');
assert.deepEqual(JSON.parse(calls.find((call) => call.path.endsWith('/disable')).body), { version: 3, reason: '不符合当前协议' }, 'disable body must be version and auditable reason only');
assert.equal(calls.filter((call) => call.path.endsWith('/disable')).length, 1, 'a busy administrative action must not submit a duplicate write');
await waitFor(() => dom.window.document.body.textContent.includes('操作已提交，但最新服务端记录读取失败'), 'a failed post-command readback must not claim the latest records were read');
assert.equal(dom.window.document.body.textContent.includes('已读取最新服务端记录'), false, 'failed post-command readback must not falsely claim a successful read');
failDistributors = false;
holdDisable = true;
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '停用').click();
await waitFor(() => confirmations.length === 1, 'delayed disable must open confirmation before transport');
resolveConfirmation({ confirmed: true, values: { reason: '跨标签读回' } });
await waitFor(() => pendingDisables.length === 1, 'delayed disable did not start');
holdLists = true;
const pendingOrdersAt = pendingLists.length;
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '订单').click();
await waitFor(() => pendingLists.length === pendingOrdersAt + 1, 'orders did not remain pending while the distributor mutation completed');
pendingDisables.shift()(json({}));
await waitFor(() => dom.window.document.body.textContent.includes('操作已提交，但列表已切换或读取已过期'), 'a switched tab must not be treated as a successful original-tab readback');
pendingLists[pendingOrdersAt].resolve(json({ items: [{ attribution_id: 11, order_reference: 'O-9', product_name: '增长课' }], next_cursor: '' }));
await waitFor(() => dom.window.document.body.textContent.includes('O-9'), 'the pending current-tab read must survive a stale original-tab readback');
assert.equal(dom.window.document.body.textContent.includes('O-9'), true, 'a stale mutation readback must not replace the current tab');
assert.equal(dom.window.document.body.textContent.includes('已读取最新服务端记录'), false, 'a stale mutation readback must not claim the original tab was refreshed');
holdDisable = false;
holdLists = false;
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '异常').click();
await waitFor(() => dom.window.document.body.textContent.includes('异常待确认'), 'exception list did not render');
assert.equal(dom.window.document.body.textContent.includes('接收方收款额度已达上限，请核验额度'), true, 'bounded Payment failure class must give administrators a concrete Chinese action');
assert.match(dom.window.document.body.textContent, /尚欠\s+¥0\.12/, 'exception list unpaid money must use the read model currency');
assert.match(dom.window.document.body.textContent, /系统分账成功确认\s+¥0\.33/, 'exception list paid money must use the read model currency');
failExceptions = true;
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '登记追回').click();
await waitFor(() => confirmations.length === 1, 'recovery must open confirmation before transport');
assert.match(confirmations[0].options.description, /异常编号 x1/, 'recovery confirmation identifies its frozen exception target');
resolveConfirmation({ confirmed: true, values: { amount_minor: '12', evidence_reference: 'receipt-1' } });
await waitFor(() => calls.some((call) => call.path.endsWith('/recoveries')), 'recovery did not call real endpoint');
const recoveryCalls = calls.filter((call) => call.path.endsWith('/recoveries'));
assert.deepEqual(JSON.parse(recoveryCalls[0].body), { version: 4, amount_minor: 12, evidence_reference: 'receipt-1' }, 'manual recovery cannot claim WeChat payout and must include evidence');
await waitFor(() => dom.window.document.body.textContent.includes('提交结果仍未确认，最新服务端记录读取失败'), 'an unconfirmed command and failed readback must remain explicit');
assert.equal(dom.window.document.body.textContent.includes('异常待确认'), true, 'a failed command readback must preserve the selected exception tab rather than covering it with another tab');
assert.equal(dom.window.document.body.textContent.includes('已读取最新服务端记录'), false, 'a failed command plus failed readback must not claim a confirmed refresh');
failExceptions = false;
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '登记追回').click();
await waitFor(() => confirmations.length === 1, 'recovery retry must open a new confirmation');
resolveConfirmation({ confirmed: true, values: { amount_minor: '12', evidence_reference: 'receipt-1' } });
await waitFor(() => calls.filter((call) => call.path.endsWith('/recoveries')).length === 2, 'recovery retry did not submit');
const retriedRecoveryCalls = calls.filter((call) => call.path.endsWith('/recoveries'));
assert.equal(retriedRecoveryCalls[1].idempotencyKey, retriedRecoveryCalls[0].idempotencyKey, 'unknown recovery retry must reuse the original idempotency key');
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '登记商户承担').click();
await waitFor(() => confirmations.length === 1, 'liability must open confirmation before transport');
assert.match(confirmations[0].options.description, /异常编号 x1/, 'liability confirmation identifies its frozen exception target');
resolveConfirmation({ confirmed: true, values: { amount_minor: '8', reason: '商户承担原因' } });
await waitFor(() => calls.some((call) => call.path.endsWith('/merchant-liabilities')), 'merchant liability did not call real endpoint');
assert.deepEqual(JSON.parse(calls.find((call) => call.path.endsWith('/merchant-liabilities')).body), { version: 4, amount_minor: 8, reason: '商户承担原因' }, 'merchant liability must carry only frozen amount and reason');
assert.equal(calls.some((call) => /paid|wechat/i.test(call.path)), false, 'admin UI must not invent a manual WeChat-paid action');
await delay(40);
dom.window.close();
console.log('distribution admin contract: PASS');
