import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { build } from 'esbuild';
import { JSDOM } from 'jsdom';
import { fileURLToPath } from 'node:url';
import { memberGridPresentationPlugin, deriveMemberGridPresentation } from '../../scripts/member-grid-presentation-source.mjs';

const source = await fs.readFile(new URL('../src/public/memberGridShare.ts', import.meta.url), 'utf8');
assert.throws(() => deriveMemberGridPresentation(source + '\n'), /digest mismatch/);
const bundle = await build({ entryPoints: [fileURLToPath(new URL('./memberGridFeedbackHost.ts', import.meta.url))], bundle: true, write: false, format: 'iife', plugins: [memberGridPresentationPlugin] });
const wait = () => new Promise(resolve => setTimeout(resolve, 10));
const token = 'mgshare1.' + 'a'.repeat(16) + '.' + 'b'.repeat(43);
const page = (name, more) => ({ as_of: '2026-09-09', buckets: ['active','expired','removed'].map(state => ({ state, count: 1 })), rows: [{ display_name: name, state: 'active', source: 'manual', starts_at: '2026-09-01', updated_at: '2026-09-09' }], limit: 50, next_cursor: more ? 'next' : '', has_more: more });
const dom = new JSDOM('<div id="stage"></div>', { url: 'https://example.test/member-grid-share/#' + token, runScripts: 'outside-only' });
const pending = [];
const calls = [];
dom.window.fetch = (url, options) => { calls.push({url, options}); return new Promise(resolve => pending.push(resolve)); };
dom.window.eval(bundle.outputFiles[0].text);
assert.equal(dom.window.location.hash, '');
pending.shift()({ ok: true, json: async () => page('第一位', true) });
await wait();
assert.ok(dom.window.document.querySelector('.v3-share-table-scroll table'));
let button = dom.window.document.querySelector('button');
const unavailable = dom.window.document.createElement('button');
unavailable.disabled = true;
unavailable.textContent = '原本不可用';
dom.window.document.querySelector('#stage').append(unavailable);
button.click(); button.click();
assert.equal(calls.length, 2, 'double click must issue one next-page read');
assert.equal(button.disabled, true);
pending.shift()({ ok: false });
await wait();
assert.match(dom.window.document.body.textContent, /第一位/);
assert.match(dom.window.document.body.textContent, /已保留当前列表/);
assert.equal(unavailable.disabled, true, 'read completion must preserve pre-existing disabled controls');
unavailable.remove();
dom.window.document.querySelector('[data-share-read-error] button').click();
assert.equal(calls.length, 3);
pending.shift()({ ok: true, json: async () => page('第二位', false) });
await wait();
assert.equal(dom.window.document.querySelectorAll('tbody tr').length, 2);
assert.equal(dom.window.document.querySelector('[data-share-read-error]'), null);
assert.equal(dom.window.document.querySelector('button'), null);
for (const call of calls) {
  assert.equal(call.options.method, 'POST');
  assert.equal(call.options.credentials, 'omit');
  assert.equal(JSON.parse(call.options.body).token, token);
}
assert.equal(JSON.parse(calls[1].options.body).cursor, JSON.parse(calls[2].options.body).cursor);
dom.window.close();
// First-page failure keeps the original closure usable after token removal.
const first = new JSDOM('<div id="stage"></div>', { url: 'https://example.test/member-grid-share/#' + token, runScripts: 'outside-only' });
let attempts = 0;
first.window.fetch = async () => ++attempts === 1 ? {ok:false} : {ok:true,json:async()=>page('重试结果',false)};
first.window.eval(bundle.outputFiles[0].text);
await wait();
first.window.document.querySelector('button').click();
await wait();
assert.match(first.window.document.body.textContent, /重试结果/);
assert.equal(first.window.location.hash, '');
first.window.close();
console.log('member-grid feedback: duplicate clicks, retained rows, retry, frozen source and token protocol passed');
