import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { JSDOM } from 'jsdom';
import { buildTestBrowserBundle } from '../scripts/test-browser-bundle.mjs';

const bundle = await buildTestBrowserBundle(fileURLToPath(new URL('./referralAdmin.ts', import.meta.url)));
const delay = (ms = 8) => new Promise((resolve) => setTimeout(resolve, ms));
async function waitFor(check, description) { for (let index = 0; index < 150; index++) { if (check()) return; await delay(); } throw new Error(description); }
const json = (body, status = 200) => new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } });
const campaign = { id: 7, name: '秋日组队赛', state: 'active', effective_state: 'active', version: 3, starts_at: '2026-09-20T00:00:00Z', ends_at: '2026-10-01T00:00:00Z', description: '邀请好友一起参加。', reward_rules: '按活动规则发奖。', participant_count: 4, invitation_count: 3, team_count: 1 };
const campaignB = { ...campaign, id: 8, name: '冬日同行赛' };
const calls = [];
const dom = new JSDOM('<!doctype html><main id="referral-admin-root"></main>', { url: 'https://crm.example/admin/referral', runScripts: 'outside-only', pretendToBeVisual: true, beforeParse(window) {
  window.Response = Response; window.Headers = Headers; window.URL = URL;
  window.HTMLDialogElement.prototype.showModal = function () { this.setAttribute('open', ''); };
  window.HTMLDialogElement.prototype.close = function () { this.removeAttribute('open'); this.dispatchEvent(new window.Event('close')); };
  window.URL.createObjectURL = () => 'blob:referral-export'; window.URL.revokeObjectURL = () => undefined;
  window.HTMLAnchorElement.prototype.click = function () { this.dataset.downloaded = 'true'; };
  window.fetch = async (input, init = {}) => { const url = new URL(String(input), window.location.href); calls.push({ path: url.pathname, query: url.search, method: String(init.method || 'GET'), body: String(init.body || '') });
    if (url.pathname === '/api/admin/referral/campaigns' && (!init.method || init.method === 'GET')) return json({ items: [campaign, campaignB], next_cursor: '' });
    if (url.pathname === '/api/admin/referral/campaigns/7' && (!init.method || init.method === 'GET')) return json({ ...campaign, teams: [{ id: 3, name: '冲刺队' }], daily_metrics: [{ date: '2026-09-20', participant_count: 2, invitation_count: 1 }], team_summaries: [{ id: 3, name: '冲刺队', captain_name: '可信队长', participant_count: 2, direct_invitation_count: 1, captain_participated: true }] });
    if (url.pathname === '/api/admin/referral/campaigns/7/participants') return url.searchParams.get('cursor') === 'page-2' ? json({ items: [{ participation_id: 13, participant_name: '第二页成员', team_name: '冲刺队', inviter_name: '', direct_invitation_count: 0, joined_at: '2026-09-20T00:02:00Z', state: 'active' }], next_cursor: '' }) : json({ items: [{ participation_id: 11, participant_name: '零邀请成员', team_name: '冲刺队', inviter_name: '', direct_invitation_count: 0, joined_at: '2026-09-20T00:00:00Z', state: 'active' }], next_cursor: 'page-2' });
    if (url.pathname === '/api/admin/referral/campaigns/7/participants/11/invitations') return json({ items: [{ participation_id: 12, inviter_name: '零邀请成员', inviter_team_name: '冲刺队', participant_name: '被邀请成员', participant_team_name: '冲刺队', joined_at: '2026-09-20T00:01:00Z', score_state: 'valid' }] });
    if (url.pathname === '/api/admin/referral/campaigns/8' && (!init.method || init.method === 'GET')) return json({ ...campaignB, teams: [], team_summaries: [], daily_metrics: [] });
    if (url.pathname === '/api/admin/referral/campaigns/8/participants') return json({ items: [{ participation_id: 21, participant_name: '活动 B 成员', team_name: '', inviter_name: '', direct_invitation_count: 0, joined_at: '2026-09-20T00:03:00Z', state: 'active' }], next_cursor: '' });
    if (url.pathname === '/api/admin/referral/campaigns/8/invitations') return json({ items: [{ participation_id: 22, inviter_name: '活动 B 邀请人', inviter_team_name: '', participant_name: '活动 B 受邀人', participant_team_name: '', joined_at: '2026-09-20T00:04:00Z', score_state: 'valid' }], next_cursor: '' });
    if (url.pathname === '/api/admin/referral/campaigns/7/export') return new Response('\ufeff成员,所属战队\r\n零邀请成员,冲刺队\r\n', { headers: { 'Content-Type': 'text/csv; charset=utf-8' } });
    if (url.pathname === '/api/admin/customers') return json({ items: [{ customer_id: 101, display_name: '可信客户' }] });
    if (url.pathname === '/api/admin/referral/campaigns/7/teams') return json({ id: 3, name: '冲刺队' }, 201);
    return json({ error: 'not_found' }, 404);
  };
} });
dom.window.eval(bundle);
await waitFor(() => dom.window.document.body.textContent.includes('秋日组队赛'), 'campaign list did not render');
assert.equal(dom.window.document.querySelector('nav'), null, 'top-level list must not duplicate the CRM shell navigation');
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '查看活动详情').click();
await waitFor(() => dom.window.document.body.textContent.includes('零邀请成员'), 'default activity detail did not load members');
assert.match(dom.window.document.body.textContent, /参与人数[\s\S]*4/, 'detail needs real participant metric');
assert.match(dom.window.document.body.textContent, /零邀请成员[\s\S]*0/, 'members include zero-invitation participant');
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '加载更多').click();
await waitFor(() => dom.window.document.body.textContent.includes('第二页成员'), 'next_cursor must append the following member page');
assert.equal(dom.window.document.body.textContent.includes('零邀请成员'), true, 'loading another page must retain earlier rows');
assert.equal([...dom.window.document.querySelectorAll('nav button')].some((item) => item.textContent === '邀请撤销'), false, 'revocations must not be a duplicate top-level tab');
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '查看邀请对象').click();
await waitFor(() => dom.window.document.body.textContent.includes('被邀请成员'), 'member drilldown must use immutable participation target');
assert.match(dom.window.document.body.textContent, /被邀请成员/, 'drilldown did not render invitations');
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '导出当前筛选').click();
await waitFor(() => calls.some((call) => call.path === '/api/admin/referral/campaigns/7/export' && /participation_id=11/.test(call.query)), 'drilldown export must stay scoped to its participation');
const drilldownExport = calls.find((call) => call.path === '/api/admin/referral/campaigns/7/export' && /participation_id=11/.test(call.query));
assert.equal(/team_id=/.test(drilldownExport.query), false, 'drilldown export cannot send an unrelated team filter');
const teamsTab = [...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '战队'); teamsTab.click();
await waitFor(() => dom.window.document.body.textContent.includes('可信队长'), 'team summary did not render safe captain name');
assert.match(dom.window.document.body.textContent, /已确认队员[\s\S]*2/, 'team summary needs confirmed participant count');
assert.equal([...dom.window.document.querySelectorAll('.referral-admin-table button')].some((button) => button.textContent === '查看队员'), true, 'team rows need a member drilldown');
assert.equal([...dom.window.document.querySelectorAll('.referral-admin-table button')].some((button) => button.textContent === '队长参加入口'), true, 'team rows need a captain-owned participation entry');
[...dom.window.document.querySelectorAll('.referral-admin-table button')].find((button) => button.textContent === '查看队员').click();
await waitFor(() => dom.window.document.querySelector('[aria-label="战队筛选"]')?.value === '3', 'team member drilldown did not apply the team filter');
assert.equal(calls.some((call) => call.path === '/api/admin/referral/campaigns/7/participants' && /team_id=3/.test(call.query)), true, 'team member drilldown must use the campaign-scoped team filter');
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '战队').click();
await waitFor(() => [...dom.window.document.querySelectorAll('.referral-admin-table button')].some((button) => button.textContent === '队长参加入口'), 'team controls did not return after member drilldown');
[...dom.window.document.querySelectorAll('.referral-admin-table button')].find((button) => button.textContent === '队长参加入口').click();
await waitFor(() => dom.window.document.querySelector('dialog[data-shared-qr-dialog="true"]'), 'captain join entry did not open a real QR dialog');
assert.equal(dom.window.document.querySelector('[data-shared-qr-dialog="true"] input')?.value, 'https://crm.example/referral?campaign=7', 'captain entry must be a same-origin campaign login path');
assert.equal(Boolean(dom.window.document.querySelector('[data-shared-qr-dialog="true"] [data-qr-payload]')), true, 'captain join entry needs a real QR payload');
dom.window.document.querySelector('[data-shared-qr-dialog="true"]').close();
dom.window.document.querySelector('[data-testid="referral-admin-create-team"]').click();
const dialog = dom.window.document.querySelector('[data-testid="referral-admin-dialog"]'); const fields = dialog.querySelectorAll('input'); fields[0].value = '新战队'; fields[2].value = '可信'; [...dialog.querySelectorAll('button')].find((button) => button.textContent === '搜索客户').click();
await waitFor(() => dialog.textContent.includes('可信客户'), 'captain picker did not query authorized directory');
[...dialog.querySelectorAll('button')].find((button) => button.textContent === '可信客户').click(); [...dialog.querySelectorAll('button')].find((button) => button.textContent === '创建战队').click();
await waitFor(() => calls.some((call) => call.path.endsWith('/campaigns/7/teams') && call.method === 'POST'), 'team create did not call actual endpoint');
const teamWrite = calls.find((call) => call.path.endsWith('/campaigns/7/teams') && call.method === 'POST'); assert.deepEqual(JSON.parse(teamWrite.body), { name: '新战队', logo_url: '', captain_customer_id: 101 }, 'team command only uses a selected directory identity');
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '← 活动列表').click();
await waitFor(() => dom.window.document.body.textContent.includes('冬日同行赛'), 'returning to activities did not render campaign B');
const campaignBCard = [...dom.window.document.querySelectorAll('.referral-admin-campaign')].find((card) => card.textContent.includes('冬日同行赛'));
[...campaignBCard.querySelectorAll('button')].find((button) => button.textContent === '查看活动详情').click();
await waitFor(() => dom.window.document.body.textContent.includes('活动 B 成员'), 'campaign B detail did not load its own participants');
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '邀请明细').click();
await waitFor(() => dom.window.document.body.textContent.includes('活动 B 受邀人'), 'campaign B invitations retained stale campaign A drilldown');
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '导出当前筛选').click();
await waitFor(() => calls.some((call) => call.path === '/api/admin/referral/campaigns/8/export'), 'campaign B export was not requested');
const campaignBExport = calls.filter((call) => call.path === '/api/admin/referral/campaigns/8/export').at(-1);
assert.equal(/participation_id=/.test(campaignBExport.query), false, 'campaign B export must clear campaign A drilldown scope');
dom.window.close();
console.log('referralAdmin behavior passed');

await import("./referralSettings.test.mjs");
