const root=document.getElementById('invitationWorkspace');
if(root){
 const $=id=>document.getElementById(id),form=$('invitationForm');
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const names={legacy:'待绑定升级',active:'承接中',paused:'已暂停',full:'待补群',stale:'群信息过期',preparing:'群码准备中',ready:'已同步',failed:'同步异常',pending:'群昵称待同步',queued:'等待执行',running:'刷新中',completed:'已完成',partial:'部分完成'};
 const groupName=g=>g?.observed_at?(g.name||'未命名群'):'群昵称待同步';
 const when=v=>v&&!String(v).startsWith('0001-')?new Date(v).toLocaleString():'等待首次同步';
 const cache=new Map();let plans=[],selected=[],editing=null,offset=0,total=0,optionOffset=0,busy=false,writeEnabled=false;
 function notice(v){$('invitationNotice').textContent=v;}
 function csrf(){for(const c of document.cookie.split(';')){const p=c.trim();for(const k of ['aicrm_admin_csrf=','aicrm_csrf='])if(p.startsWith(k))return decodeURIComponent(p.slice(k.length));}return '';}
 async function api(path,body){const headers={};if(body!==undefined){headers['Content-Type']='application/json';headers['X-CSRF-Token']=csrf();headers['Idempotency-Key']=crypto.randomUUID();}const r=await fetch('/api/admin/'+path,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers,body:body===undefined?undefined:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw new Error(r.status===403?'当前账号无权限，或页面安全令牌已失效':r.status===401?'登录已过期，请重新登录':v.error||'操作失败，请重试');return v;}
 async function getGroup(id){if(!cache.has(id)){const g=await api('group-directory/'+encodeURIComponent(id));cache.set(id,g);}return cache.get(id);}
 function tab(name){for(const b of root.querySelectorAll('[data-tab]'))b.setAttribute('aria-selected',String(b.dataset.tab===name));$('directoryPanel').hidden=name!=='directory';$('plansPanel').hidden=name!=='plans';$('invitationEditor').hidden=true;$('invitationHistory').hidden=true;}
 async function loadPlans(){const v=await api('group-invitations');plans=v.items;writeEnabled=Boolean(v.write_enabled);$('createInvitation').disabled=!writeEnabled;for(const p of plans){for(const b of p.bindings){try{await getGroup(b.chat_id);}catch{}}}
 $('invitationRows').innerHTML=plans.map(p=>{const g=cache.get(p.current_chat_id),ready=p.enabled&&p.state==='active'&&p.current_chat_id&&['executed','reconciled'].includes(p.provider_state)&&p.provider_config_id&&p.provider_qr_code;return `<tr><td>${esc(p.name)}</td><td>${!p.token?'旧邀请':p.mode==='single'?'固定单群':`多群 · ${p.threshold} 人`}</td><td>${p.current_chat_id?`${esc(groupName(g))}<br><code>${esc(p.current_chat_id)}</code>`:'—'}</td><td>${g?.observed_at?g.member_count:'—'}<br>${esc(when(g?.observed_at))}</td><td>${esc(names[p.state]||p.state)}</td><td><button class="aud-btn" data-edit="${p.id}">${p.token?'编辑':'绑定升级'}</button><button class="aud-btn" data-link="${p.id}">复制链接</button>${p.token&&!p.provider_state&&p.enabled?`<button class="aud-btn" data-upgrade="${p.id}" ${writeEnabled?'':'disabled'}>升级固定企微码</button>`:''}<button class="aud-btn" data-qr="${p.id}" ${ready?'':'disabled'} title="${ready?'下载企微官方二维码':'固定企微码确认后可下载'}">下载企微入群码</button><button class="aud-btn" data-history="${p.id}">切换记录</button></td></tr>`;}).join('')||'<tr><td colspan="6">暂无邀请计划</td></tr>';
 }
 async function status(){const s=await api('group-directory/status'),r=s.run;$('directoryStatus').textContent=!s.enabled?'群聊同步尚未启用，请先检查企微群聊读取配置。':`每 24 小时自动同步 · 下次：${when(s.next_auto_at)}${r?` · ${names[r.state]||r.state} · 已发现 ${r.discovered}，新增 ${r.added}，更新 ${r.updated}，失败 ${r.failed}`:''}${s.rerun_requested?' · 本轮结束后将补充刷新':''}`;$('refreshDirectory').disabled=!s.enabled;return s;}
 async function directory(){const q=new FormData($('directorySearch')).get('q')||'';const p=await api(`group-directory?q=${encodeURIComponent(q)}&limit=50&offset=${offset}`);total=p.total;for(const g of p.items)cache.set(g.chat_id,g);$('directoryRows').innerHTML=p.items.map(g=>`<tr><td>${esc(groupName(g))}</td><td><code>${esc(g.chat_id)}</code> <button class="aud-btn" data-copy="${esc(g.chat_id)}">复制</button></td><td>${esc(g.owner_user_id||'待同步')}</td><td>${g.observed_at?g.member_count:'—'}</td><td>${esc(when(g.observed_at))}</td><td>${esc(names[g.sync_state]||g.sync_state)}</td></tr>`).join('')||'<tr><td colspan="6">暂无群聊，可点击“一键刷新群聊”</td></tr>';$('directoryPage').textContent=`共 ${total} 个 · 第 ${Math.floor(offset/50)+1} 页`;$('directoryPrev').disabled=offset===0;$('directoryNext').disabled=offset+50>=total;await status();}
 function renderSelected(){$('selectedInvitationGroups').innerHTML=selected.map((id,i)=>{const retired=editing?.bindings.find(b=>b.chat_id===id)?.retired;const locked=retired||(editing?.mode==='sequence'&&editing?.current_chat_id===id);return `<li>${esc(groupName(cache.get(id)))} <code>${esc(id)}</code> ${retired?'已切出':''}<button class="aud-btn" type="button" data-up="${i}" ${locked||i===0?'disabled':''}>上移</button><button class="aud-btn" type="button" data-remove="${i}" ${locked?'disabled':''}>移除</button></li>`;}).join('');}
 async function options(reset=true){if(reset)optionOffset=0;const p=await api(`group-directory?q=${encodeURIComponent($('invitationGroupQuery').value)}&limit=50&offset=${optionOffset}`);for(const g of p.items)cache.set(g.chat_id,g);const html=p.items.map(g=>`<tr><td>${esc(groupName(g))}</td><td><code>${esc(g.chat_id)}</code></td><td>${g.observed_at?g.member_count:'—'}</td><td><button type="button" class="aud-btn" data-add="${esc(g.chat_id)}" ${!g.observed_at?'disabled':''}>添加</button></td></tr>`).join('');if(reset)$('invitationGroupOptions').innerHTML=html;else $('invitationGroupOptions').insertAdjacentHTML('beforeend',html);optionOffset+=p.items.length;$('groupOptionsMore').hidden=optionOffset>=p.total;}
 function mode(){const multi=form.elements.mode.value==='sequence';$('thresholdField').hidden=!multi;form.elements.threshold.required=multi;$('invitationRuleNote').textContent=multi?'按配置顺序承接，达到阈值时切换。已切出的群不会回流；实际人数可能因同步间隔超过阈值。':'固定使用一个群，不自动轮替。选择其他群可替换当前绑定。';}
 async function edit(plan){tab('plans');editing=plan;selected=plan?plan.bindings.map(b=>b.chat_id):[];form.reset();form.elements.name.value=plan?.name||'';form.elements.title.value=plan?.title||'';form.elements.description.value=plan?.description||'';form.elements.mode.value=plan?.mode||'single';form.elements.mode.disabled=Boolean(plan?.token);form.elements.threshold.value=plan?.threshold??'';form.elements.enabled.checked=plan?.enabled??true;mode();renderSelected();$('plansPanel').hidden=true;$('directoryPanel').hidden=true;$('invitationEditor').hidden=false;$('editorTitle').textContent=plan?'编辑邀请计划':'新建邀请计划';await options();}
 async function run(fn){try{await fn();}catch(e){notice(e.message);}}
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;run(async()=>{
 if(b.dataset.tab){tab(b.dataset.tab);if(b.dataset.tab==='directory')await directory();else await loadPlans();}
 if(b.dataset.copy){await navigator.clipboard.writeText(b.dataset.copy);notice('已复制群 ID');}
 if(b.dataset.edit)await edit(plans.find(p=>p.id===Number(b.dataset.edit)));
 if(b.dataset.link){await navigator.clipboard.writeText(plans.find(p=>p.id===Number(b.dataset.link)).join_url);notice('已复制邀请链接');}
 if(b.dataset.upgrade){const p=plans.find(p=>p.id===Number(b.dataset.upgrade));if(!p||!writeEnabled||p.provider_state){notice('当前计划不能升级固定码');return;}await api('group-invitations',{id:p.id,version:p.version,name:p.name,title:p.title,description:p.description,cover_image_id:p.cover_image_id,mode:p.mode,threshold:p.threshold,enabled:p.enabled,chat_ids:p.bindings.map(v=>v.chat_id)});notice('已提交固定企微码生成，企微确认后可下载');await loadPlans();}
 if(b.dataset.qr){const p=plans.find(p=>p.id===Number(b.dataset.qr));if(!p)return;b.disabled=true;try{const r=await fetch(`/api/admin/group-invitations/${p.id}/qr-download`,{credentials:'same-origin',cache:'no-store'});if(!r.ok)throw new Error(r.status===409?'固定企微码尚未确认，请稍后刷新':'企微二维码下载失败，请稍后重试');const blob=await r.blob();if(blob.type!=='image/png')throw new Error('企微二维码格式异常');const href=URL.createObjectURL(blob),a=document.createElement('a');a.href=href;a.download=`企微入群码-${p.id}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(href),30000);notice('已生成企微官方二维码下载');}finally{b.disabled=false;}}
 if(b.dataset.history){const h=await api(`group-invitations/${b.dataset.history}/history`);$('invitationHistoryRows').innerHTML=h.items.map(v=>`<p>${esc(when(v.at))}：${esc(groupName(cache.get(v.from)))} ${esc(v.from||'无')} → ${esc(groupName(cache.get(v.to)))} ${esc(v.to||'暂无承接群')}</p>`).join('')||'<p>暂无切换记录</p>';$('invitationHistory').hidden=false;}
 if(b.dataset.add){if(form.elements.mode.value==='single')selected=[b.dataset.add];else if(!selected.includes(b.dataset.add))selected.push(b.dataset.add);renderSelected();}
 if(b.dataset.remove!==undefined){selected.splice(Number(b.dataset.remove),1);renderSelected();}
 if(b.dataset.up!==undefined){const i=Number(b.dataset.up),prev=selected[i-1];if(editing?.bindings.find(x=>x.chat_id===prev)?.retired||editing?.current_chat_id===prev){notice('当前承接群及已切出群不能调整顺序');return;}[selected[i-1],selected[i]]=[selected[i],selected[i-1]];renderSelected();}
 });});
 $('createInvitation').onclick=()=>run(()=>edit(null));$('cancelInvitation').onclick=()=>tab('plans');$('closeInvitationHistory').onclick=()=>$('invitationHistory').hidden=true;
 $('refreshDirectory').onclick=()=>run(async()=>{await api('group-directory/refresh',{});notice('已发起全量刷新，完成后自动更新目录');tab('directory');await directory();});
 $('directorySearch').onsubmit=e=>{e.preventDefault();offset=0;run(directory);};$('directoryPrev').onclick=()=>{offset=Math.max(0,offset-50);run(directory);};$('directoryNext').onclick=()=>{offset+=50;run(directory);};
 $('findInvitationGroup').onclick=()=>run(()=>options());$('groupOptionsMore').onclick=()=>run(()=>options(false));form.elements.mode.onchange=mode;
 form.onsubmit=e=>{e.preventDefault();if(busy)return;run(async()=>{busy=true;try{if(!selected.length){notice('请先选择承接群聊');return;}const input={id:editing?.id||0,version:editing?.version||0,name:form.elements.name.value.trim(),title:form.elements.title.value.trim(),description:form.elements.description.value,cover_image_id:editing?.cover_image_id||0,mode:form.elements.mode.value,threshold:form.elements.mode.value==='sequence'?Number(form.elements.threshold.value):null,enabled:form.elements.enabled.checked,chat_ids:selected};await api('group-invitations',input);notice('已保存，官方群码确认成功后可入群');tab('plans');await loadPlans();}finally{busy=false;}});};
 async function poll(){await run(async()=>{const s=await status();if(!$('directoryPanel').hidden&&s.run)await directory();if(!$('plansPanel').hidden){cache.clear();await loadPlans();}});setTimeout(poll,10000);}
 const actions=$('invitationActions'),topbar=document.querySelector('.admin-topbar');let header=topbar?.querySelector('.admin-topbar-meta');if(!header&&topbar){header=document.createElement('div');header.className='admin-topbar-meta';topbar.append(header);}if(header)header.append(actions);tab('plans');
 run(async()=>{await loadPlans();await status();if(new URLSearchParams(location.search).get('tab')==='directory'){tab('directory');await directory();}});setTimeout(poll,10000);
}
